// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditevent type in the database.
	Label = "audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldEntity holds the string denoting the entity field in the database.
	FieldEntity = "entity"
	// FieldEntityRef holds the string denoting the entity_ref field in the database.
	FieldEntityRef = "entity_ref"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// Table holds the table name of the auditevent in the database.
	Table = "audit_events"
)

// Columns holds all SQL columns for auditevent fields.
var Columns = []string{
	FieldID,
	FieldTs,
	FieldAction,
	FieldEntity,
	FieldEntityRef,
	FieldActor,
	FieldDetails,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTs holds the default value on creation for the "ts" field.
	DefaultTs func() time.Time
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// EntityValidator is a validator for the "entity" field. It is called by the builders before save.
	EntityValidator func(string) error
	// DefaultEntityRef holds the default value on creation for the "entity_ref" field.
	DefaultEntityRef string
	// DefaultActor holds the default value on creation for the "actor" field.
	DefaultActor string
	// DefaultDetails holds the default value on creation for the "details" field.
	DefaultDetails string
)

// OrderOption defines the ordering options for the AuditEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByEntity orders the results by the entity field.
func ByEntity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntity, opts...).ToFunc()
}

// ByEntityRef orders the results by the entity_ref field.
func ByEntityRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityRef, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByDetails orders the results by the details field.
func ByDetails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetails, opts...).ToFunc()
}
