// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BinsColumns holds the columns for the "bins" table.
	BinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "location_bins", Type: field.TypeInt},
		{Name: "zone_bins", Type: field.TypeInt},
	}
	// BinsTable holds the schema information for the "bins" table.
	BinsTable = &schema.Table{
		Name:       "bins",
		Columns:    BinsColumns,
		PrimaryKey: []*schema.Column{BinsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bins_locations_bins",
				Columns:    []*schema.Column{BinsColumns[3]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "bins_zones_bins",
				Columns:    []*schema.Column{BinsColumns[4]},
				RefColumns: []*schema.Column{ZonesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "bin_code_location_bins",
				Unique:  true,
				Columns: []*schema.Column{BinsColumns[1], BinsColumns[3]},
			},
		},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sku", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
	}
	// LocationsColumns holds the columns for the "locations" table.
	LocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// LocationsTable holds the schema information for the "locations" table.
	LocationsTable = &schema.Table{
		Name:       "locations",
		Columns:    LocationsColumns,
		PrimaryKey: []*schema.Column{LocationsColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_number", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "DRAFT"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// OrderLinesColumns holds the columns for the "order_lines" table.
	OrderLinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "item_order_lines", Type: field.TypeInt},
		{Name: "location_order_lines", Type: field.TypeInt},
		{Name: "order_lines", Type: field.TypeInt},
	}
	// OrderLinesTable holds the schema information for the "order_lines" table.
	OrderLinesTable = &schema.Table{
		Name:       "order_lines",
		Columns:    OrderLinesColumns,
		PrimaryKey: []*schema.Column{OrderLinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_lines_items_order_lines",
				Columns:    []*schema.Column{OrderLinesColumns[2]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "order_lines_locations_order_lines",
				Columns:    []*schema.Column{OrderLinesColumns[3]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "order_lines_orders_lines",
				Columns:    []*schema.Column{OrderLinesColumns[4]},
				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PickListsColumns holds the columns for the "pick_lists" table.
	PickListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Default: "CREATED"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "done_at", Type: field.TypeTime, Nullable: true},
		{Name: "order_picklist", Type: field.TypeInt, Unique: true},
	}
	// PickListsTable holds the schema information for the "pick_lists" table.
	PickListsTable = &schema.Table{
		Name:       "pick_lists",
		Columns:    PickListsColumns,
		PrimaryKey: []*schema.Column{PickListsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pick_lists_orders_picklist",
				Columns:    []*schema.Column{PickListsColumns[5]},
				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "picklist_order_picklist",
				Unique:  true,
				Columns: []*schema.Column{PickListsColumns[5]},
			},
		},
	}
	// PickTasksColumns holds the columns for the "pick_tasks" table.
	PickTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString, Default: "OPEN"},
		{Name: "picked_at", Type: field.TypeTime, Nullable: true},
		{Name: "bin_id", Type: field.TypeInt, Nullable: true},
		{Name: "order_line_pick_tasks", Type: field.TypeInt},
		{Name: "pick_list_tasks", Type: field.TypeInt},
	}
	// PickTasksTable holds the schema information for the "pick_tasks" table.
	PickTasksTable = &schema.Table{
		Name:       "pick_tasks",
		Columns:    PickTasksColumns,
		PrimaryKey: []*schema.Column{PickTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pick_tasks_order_lines_pick_tasks",
				Columns:    []*schema.Column{PickTasksColumns[5]},
				RefColumns: []*schema.Column{OrderLinesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "pick_tasks_pick_lists_tasks",
				Columns:    []*schema.Column{PickTasksColumns[6]},
				RefColumns: []*schema.Column{PickListsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "picktask_pick_list_tasks_order_line_pick_tasks",
				Unique:  true,
				Columns: []*schema.Column{PickTasksColumns[6], PickTasksColumns[5]},
			},
		},
	}
	// StockMovementsColumns holds the columns for the "stock_movements" table.
	StockMovementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "reference", Type: field.TypeString, Nullable: true},
		{Name: "item_movements", Type: field.TypeInt},
		{Name: "location_movements", Type: field.TypeInt},
	}
	// StockMovementsTable holds the schema information for the "stock_movements" table.
	StockMovementsTable = &schema.Table{
		Name:       "stock_movements",
		Columns:    StockMovementsColumns,
		PrimaryKey: []*schema.Column{StockMovementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "stock_movements_items_movements",
				Columns:    []*schema.Column{StockMovementsColumns[5]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "stock_movements_locations_movements",
				Columns:    []*schema.Column{StockMovementsColumns[6]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TrackingsColumns holds the columns for the "trackings" table.
	TrackingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tracking_id", Type: field.TypeString},
		{Name: "tracking_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "carrier", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "update_at", Type: field.TypeTime},
		{Name: "order_tracking", Type: field.TypeInt, Unique: true},
	}
	// TrackingsTable holds the schema information for the "trackings" table.
	TrackingsTable = &schema.Table{
		Name:       "trackings",
		Columns:    TrackingsColumns,
		PrimaryKey: []*schema.Column{TrackingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "trackings_orders_tracking",
				Columns:    []*schema.Column{TrackingsColumns[6]},
				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tracking_order_tracking",
				Unique:  true,
				Columns: []*schema.Column{TrackingsColumns[6]},
			},
		},
	}
	// ZonesColumns holds the columns for the "zones" table.
	ZonesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "location_zones", Type: field.TypeInt},
	}
	// ZonesTable holds the schema information for the "zones" table.
	ZonesTable = &schema.Table{
		Name:       "zones",
		Columns:    ZonesColumns,
		PrimaryKey: []*schema.Column{ZonesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "zones_locations_zones",
				Columns:    []*schema.Column{ZonesColumns[3]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "zone_code_location_zones",
				Unique:  true,
				Columns: []*schema.Column{ZonesColumns[1], ZonesColumns[3]},
			},
		},
	}
	// BinItemsColumns holds the columns for the "bin_items" table.
	BinItemsColumns = []*schema.Column{
		{Name: "bin_id", Type: field.TypeInt},
		{Name: "item_id", Type: field.TypeInt},
	}
	// BinItemsTable holds the schema information for the "bin_items" table.
	BinItemsTable = &schema.Table{
		Name:       "bin_items",
		Columns:    BinItemsColumns,
		PrimaryKey: []*schema.Column{BinItemsColumns[0], BinItemsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bin_items_bin_id",
				Columns:    []*schema.Column{BinItemsColumns[0]},
				RefColumns: []*schema.Column{BinsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "bin_items_item_id",
				Columns:    []*schema.Column{BinItemsColumns[1]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BinsTable,
		ItemsTable,
		LocationsTable,
		OrdersTable,
		OrderLinesTable,
		PickListsTable,
		PickTasksTable,
		StockMovementsTable,
		TrackingsTable,
		ZonesTable,
		BinItemsTable,
	}
)

func init() {
	BinsTable.ForeignKeys[0].RefTable = LocationsTable
	BinsTable.ForeignKeys[1].RefTable = ZonesTable
	OrderLinesTable.ForeignKeys[0].RefTable = ItemsTable
	OrderLinesTable.ForeignKeys[1].RefTable = LocationsTable
	OrderLinesTable.ForeignKeys[2].RefTable = OrdersTable
	PickListsTable.ForeignKeys[0].RefTable = OrdersTable
	PickTasksTable.ForeignKeys[0].RefTable = OrderLinesTable
	PickTasksTable.ForeignKeys[1].RefTable = PickListsTable
	StockMovementsTable.ForeignKeys[0].RefTable = ItemsTable
	StockMovementsTable.ForeignKeys[1].RefTable = LocationsTable
	TrackingsTable.ForeignKeys[0].RefTable = OrdersTable
	ZonesTable.ForeignKeys[0].RefTable = LocationsTable
	BinItemsTable.ForeignKeys[0].RefTable = BinsTable
	BinItemsTable.ForeignKeys[1].RefTable = ItemsTable
}
