// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/warhousemanagementsystem/ent/location"
)

// Location is the model entity for the Location schema.
type Location struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationQuery when eager-loading is set.
	Edges        LocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LocationEdges holds the relations/edges for other nodes in the graph.
type LocationEdges struct {
	// Movements holds the value of the movements edge.
	Movements []*StockMovement `json:"movements,omitempty"`
	// OrderLines holds the value of the order_lines edge.
	OrderLines []*OrderLine `json:"order_lines,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MovementsOrErr returns the Movements value or an error if the edge
// was not loaded in eager-loading.
func (e LocationEdges) MovementsOrErr() ([]*StockMovement, error) {
	if e.loadedTypes[0] {
		return e.Movements, nil
	}
	return nil, &NotLoadedError{edge: "movements"}
}

// OrderLinesOrErr returns the OrderLines value or an error if the edge
// was not loaded in eager-loading.
func (e LocationEdges) OrderLinesOrErr() ([]*OrderLine, error) {
	if e.loadedTypes[1] {
		return e.OrderLines, nil
	}
	return nil, &NotLoadedError{edge: "order_lines"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Location) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case location.FieldID:
			values[i] = new(sql.NullInt64)
		case location.FieldCode, location.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Location fields.
func (_m *Location) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case location.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case location.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case location.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Location.
// This includes values selected through modifiers, order, etc.
func (_m *Location) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMovements queries the "movements" edge of the Location entity.
func (_m *Location) QueryMovements() *StockMovementQuery {
	return NewLocationClient(_m.config).QueryMovements(_m)
}

// QueryOrderLines queries the "order_lines" edge of the Location entity.
func (_m *Location) QueryOrderLines() *OrderLineQuery {
	return NewLocationClient(_m.config).QueryOrderLines(_m)
}

// Update returns a builder for updating this Location.
// Note that you need to call Location.Unwrap() before calling this method if this Location
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Location) Update() *LocationUpdateOne {
	return NewLocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Location entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Location) Unwrap() *Location {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Location is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Location) String() string {
	var builder strings.Builder
	builder.WriteString("Location(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Locations is a parsable slice of Location.
type Locations []*Location
