// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/warhousemanagementsystem/ent/item"
	"github.com/mxV03/warhousemanagementsystem/ent/location"
	"github.com/mxV03/warhousemanagementsystem/ent/order"
	"github.com/mxV03/warhousemanagementsystem/ent/orderline"
)

// OrderLine is the model entity for the OrderLine schema.
type OrderLine struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderLineQuery when eager-loading is set.
	Edges                OrderLineEdges `json:"edges"`
	item_order_lines     *int
	location_order_lines *int
	order_lines          *int
	selectValues         sql.SelectValues
}

// OrderLineEdges holds the relations/edges for other nodes in the graph.
type OrderLineEdges struct {
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderLineEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderLineEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderLineEdges) LocationOrErr() (*Location, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: location.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderLine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderline.FieldID, orderline.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case orderline.ForeignKeys[0]: // item_order_lines
			values[i] = new(sql.NullInt64)
		case orderline.ForeignKeys[1]: // location_order_lines
			values[i] = new(sql.NullInt64)
		case orderline.ForeignKeys[2]: // order_lines
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderLine fields.
func (_m *OrderLine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderline.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case orderline.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case orderline.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field item_order_lines", value)
			} else if value.Valid {
				_m.item_order_lines = new(int)
				*_m.item_order_lines = int(value.Int64)
			}
		case orderline.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field location_order_lines", value)
			} else if value.Valid {
				_m.location_order_lines = new(int)
				*_m.location_order_lines = int(value.Int64)
			}
		case orderline.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_lines", value)
			} else if value.Valid {
				_m.order_lines = new(int)
				*_m.order_lines = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderLine.
// This includes values selected through modifiers, order, etc.
func (_m *OrderLine) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the OrderLine entity.
func (_m *OrderLine) QueryOrder() *OrderQuery {
	return NewOrderLineClient(_m.config).QueryOrder(_m)
}

// QueryItem queries the "item" edge of the OrderLine entity.
func (_m *OrderLine) QueryItem() *ItemQuery {
	return NewOrderLineClient(_m.config).QueryItem(_m)
}

// QueryLocation queries the "location" edge of the OrderLine entity.
func (_m *OrderLine) QueryLocation() *LocationQuery {
	return NewOrderLineClient(_m.config).QueryLocation(_m)
}

// Update returns a builder for updating this OrderLine.
// Note that you need to call OrderLine.Unwrap() before calling this method if this OrderLine
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderLine) Update() *OrderLineUpdateOne {
	return NewOrderLineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderLine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderLine) Unwrap() *OrderLine {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderLine is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderLine) String() string {
	var builder strings.Builder
	builder.WriteString("OrderLine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteByte(')')
	return builder.String()
}

// OrderLines is a parsable slice of OrderLine.
type OrderLines []*OrderLine
