// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/warhousemanagementsystem/ent/item"
	"github.com/mxV03/warhousemanagementsystem/ent/location"
	"github.com/mxV03/warhousemanagementsystem/ent/order"
	"github.com/mxV03/warhousemanagementsystem/ent/orderline"
	"github.com/mxV03/warhousemanagementsystem/ent/predicate"
)

// OrderLineUpdate is the builder for updating OrderLine entities.
type OrderLineUpdate struct {
	config
	hooks    []Hook
	mutation *OrderLineMutation
}

// Where appends a list predicates to the OrderLineUpdate builder.
func (_u *OrderLineUpdate) Where(ps ...predicate.OrderLine) *OrderLineUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderLineUpdate) SetQuantity(v int) *OrderLineUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderLineUpdate) SetNillableQuantity(v *int) *OrderLineUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderLineUpdate) AddQuantity(v int) *OrderLineUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *OrderLineUpdate) SetOrderID(id int) *OrderLineUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderLineUpdate) SetOrder(v *Order) *OrderLineUpdate {
	return _u.SetOrderID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_u *OrderLineUpdate) SetItemID(id int) *OrderLineUpdate {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *OrderLineUpdate) SetItem(v *Item) *OrderLineUpdate {
	return _u.SetItemID(v.ID)
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (_u *OrderLineUpdate) SetLocationID(id int) *OrderLineUpdate {
	_u.mutation.SetLocationID(id)
	return _u
}

// SetLocation sets the "location" edge to the Location entity.
func (_u *OrderLineUpdate) SetLocation(v *Location) *OrderLineUpdate {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the OrderLineMutation object of the builder.
func (_u *OrderLineUpdate) Mutation() *OrderLineMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderLineUpdate) ClearOrder() *OrderLineUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *OrderLineUpdate) ClearItem() *OrderLineUpdate {
	_u.mutation.ClearItem()
	return _u
}

// ClearLocation clears the "location" edge to the Location entity.
func (_u *OrderLineUpdate) ClearLocation() *OrderLineUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderLineUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderLineUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderLineUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderLineUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderLineUpdate) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderline.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderLine.quantity": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.order"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.item"`)
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.location"`)
	}
	return nil
}

func (_u *OrderLineUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderline.Table, orderline.Columns, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.OrderTable,
			Columns: []string{orderline.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.OrderTable,
			Columns: []string{orderline.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.ItemTable,
			Columns: []string{orderline.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.ItemTable,
			Columns: []string{orderline.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.LocationTable,
			Columns: []string{orderline.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.LocationTable,
			Columns: []string{orderline.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderLineUpdateOne is the builder for updating a single OrderLine entity.
type OrderLineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderLineMutation
}

// SetQuantity sets the "quantity" field.
func (_u *OrderLineUpdateOne) SetQuantity(v int) *OrderLineUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderLineUpdateOne) SetNillableQuantity(v *int) *OrderLineUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderLineUpdateOne) AddQuantity(v int) *OrderLineUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *OrderLineUpdateOne) SetOrderID(id int) *OrderLineUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderLineUpdateOne) SetOrder(v *Order) *OrderLineUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_u *OrderLineUpdateOne) SetItemID(id int) *OrderLineUpdateOne {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *OrderLineUpdateOne) SetItem(v *Item) *OrderLineUpdateOne {
	return _u.SetItemID(v.ID)
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (_u *OrderLineUpdateOne) SetLocationID(id int) *OrderLineUpdateOne {
	_u.mutation.SetLocationID(id)
	return _u
}

// SetLocation sets the "location" edge to the Location entity.
func (_u *OrderLineUpdateOne) SetLocation(v *Location) *OrderLineUpdateOne {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the OrderLineMutation object of the builder.
func (_u *OrderLineUpdateOne) Mutation() *OrderLineMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderLineUpdateOne) ClearOrder() *OrderLineUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *OrderLineUpdateOne) ClearItem() *OrderLineUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// ClearLocation clears the "location" edge to the Location entity.
func (_u *OrderLineUpdateOne) ClearLocation() *OrderLineUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Where appends a list predicates to the OrderLineUpdate builder.
func (_u *OrderLineUpdateOne) Where(ps ...predicate.OrderLine) *OrderLineUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderLineUpdateOne) Select(field string, fields ...string) *OrderLineUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderLine entity.
func (_u *OrderLineUpdateOne) Save(ctx context.Context) (*OrderLine, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderLineUpdateOne) SaveX(ctx context.Context) *OrderLine {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderLineUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderLineUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderLineUpdateOne) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderline.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderLine.quantity": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.order"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.item"`)
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderLine.location"`)
	}
	return nil
}

func (_u *OrderLineUpdateOne) sqlSave(ctx context.Context) (_node *OrderLine, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderline.Table, orderline.Columns, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderLine.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderline.FieldID)
		for _, f := range fields {
			if !orderline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.OrderTable,
			Columns: []string{orderline.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.OrderTable,
			Columns: []string{orderline.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.ItemTable,
			Columns: []string{orderline.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.ItemTable,
			Columns: []string{orderline.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.LocationTable,
			Columns: []string{orderline.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.LocationTable,
			Columns: []string{orderline.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderLine{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
