// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/warhousemanagementsystem/ent/item"
	"github.com/mxV03/warhousemanagementsystem/ent/location"
	"github.com/mxV03/warhousemanagementsystem/ent/stockmovement"
)

// StockMovement is the model entity for the StockMovement schema.
type StockMovement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Reference holds the value of the "reference" field.
	Reference string `json:"reference,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockMovementQuery when eager-loading is set.
	Edges              StockMovementEdges `json:"edges"`
	item_movements     *int
	location_movements *int
	selectValues       sql.SelectValues
}

// StockMovementEdges holds the relations/edges for other nodes in the graph.
type StockMovementEdges struct {
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockMovementEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockMovementEdges) LocationOrErr() (*Location, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: location.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockMovement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockmovement.FieldID, stockmovement.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case stockmovement.FieldType, stockmovement.FieldReference:
			values[i] = new(sql.NullString)
		case stockmovement.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case stockmovement.ForeignKeys[0]: // item_movements
			values[i] = new(sql.NullInt64)
		case stockmovement.ForeignKeys[1]: // location_movements
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockMovement fields.
func (_m *StockMovement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockmovement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stockmovement.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case stockmovement.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case stockmovement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case stockmovement.FieldReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference", values[i])
			} else if value.Valid {
				_m.Reference = value.String
			}
		case stockmovement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field item_movements", value)
			} else if value.Valid {
				_m.item_movements = new(int)
				*_m.item_movements = int(value.Int64)
			}
		case stockmovement.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field location_movements", value)
			} else if value.Valid {
				_m.location_movements = new(int)
				*_m.location_movements = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockMovement.
// This includes values selected through modifiers, order, etc.
func (_m *StockMovement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the StockMovement entity.
func (_m *StockMovement) QueryItem() *ItemQuery {
	return NewStockMovementClient(_m.config).QueryItem(_m)
}

// QueryLocation queries the "location" edge of the StockMovement entity.
func (_m *StockMovement) QueryLocation() *LocationQuery {
	return NewStockMovementClient(_m.config).QueryLocation(_m)
}

// Update returns a builder for updating this StockMovement.
// Note that you need to call StockMovement.Unwrap() before calling this method if this StockMovement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StockMovement) Update() *StockMovementUpdateOne {
	return NewStockMovementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StockMovement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StockMovement) Unwrap() *StockMovement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockMovement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StockMovement) String() string {
	var builder strings.Builder
	builder.WriteString("StockMovement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reference=")
	builder.WriteString(_m.Reference)
	builder.WriteByte(')')
	return builder.String()
}

// StockMovements is a parsable slice of StockMovement.
type StockMovements []*StockMovement
