// Code generated by ent, DO NOT EDIT.

package picktask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mxV03/wms/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLTE(FieldID, id))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldQuantity, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldStatus, v))
}

// PickedAt applies equality check predicate on the "picked_at" field. It's identical to PickedAtEQ.
func PickedAt(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldPickedAt, v))
}

// BinID applies equality check predicate on the "bin_id" field. It's identical to BinIDEQ.
func BinID(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldBinID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLTE(FieldQuantity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PickTask {
	return predicate.PickTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PickTask {
	return predicate.PickTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PickTask {
	return predicate.PickTask(sql.FieldContainsFold(FieldStatus, v))
}

// PickedAtEQ applies the EQ predicate on the "picked_at" field.
func PickedAtEQ(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldPickedAt, v))
}

// PickedAtNEQ applies the NEQ predicate on the "picked_at" field.
func PickedAtNEQ(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldNEQ(FieldPickedAt, v))
}

// PickedAtIn applies the In predicate on the "picked_at" field.
func PickedAtIn(vs ...time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldIn(FieldPickedAt, vs...))
}

// PickedAtNotIn applies the NotIn predicate on the "picked_at" field.
func PickedAtNotIn(vs ...time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldNotIn(FieldPickedAt, vs...))
}

// PickedAtGT applies the GT predicate on the "picked_at" field.
func PickedAtGT(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldGT(FieldPickedAt, v))
}

// PickedAtGTE applies the GTE predicate on the "picked_at" field.
func PickedAtGTE(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldGTE(FieldPickedAt, v))
}

// PickedAtLT applies the LT predicate on the "picked_at" field.
func PickedAtLT(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldLT(FieldPickedAt, v))
}

// PickedAtLTE applies the LTE predicate on the "picked_at" field.
func PickedAtLTE(v time.Time) predicate.PickTask {
	return predicate.PickTask(sql.FieldLTE(FieldPickedAt, v))
}

// PickedAtIsNil applies the IsNil predicate on the "picked_at" field.
func PickedAtIsNil() predicate.PickTask {
	return predicate.PickTask(sql.FieldIsNull(FieldPickedAt))
}

// PickedAtNotNil applies the NotNil predicate on the "picked_at" field.
func PickedAtNotNil() predicate.PickTask {
	return predicate.PickTask(sql.FieldNotNull(FieldPickedAt))
}

// BinIDEQ applies the EQ predicate on the "bin_id" field.
func BinIDEQ(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldEQ(FieldBinID, v))
}

// BinIDNEQ applies the NEQ predicate on the "bin_id" field.
func BinIDNEQ(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNEQ(FieldBinID, v))
}

// BinIDIn applies the In predicate on the "bin_id" field.
func BinIDIn(vs ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldIn(FieldBinID, vs...))
}

// BinIDNotIn applies the NotIn predicate on the "bin_id" field.
func BinIDNotIn(vs ...int) predicate.PickTask {
	return predicate.PickTask(sql.FieldNotIn(FieldBinID, vs...))
}

// BinIDGT applies the GT predicate on the "bin_id" field.
func BinIDGT(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGT(FieldBinID, v))
}

// BinIDGTE applies the GTE predicate on the "bin_id" field.
func BinIDGTE(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldGTE(FieldBinID, v))
}

// BinIDLT applies the LT predicate on the "bin_id" field.
func BinIDLT(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLT(FieldBinID, v))
}

// BinIDLTE applies the LTE predicate on the "bin_id" field.
func BinIDLTE(v int) predicate.PickTask {
	return predicate.PickTask(sql.FieldLTE(FieldBinID, v))
}

// BinIDIsNil applies the IsNil predicate on the "bin_id" field.
func BinIDIsNil() predicate.PickTask {
	return predicate.PickTask(sql.FieldIsNull(FieldBinID))
}

// BinIDNotNil applies the NotNil predicate on the "bin_id" field.
func BinIDNotNil() predicate.PickTask {
	return predicate.PickTask(sql.FieldNotNull(FieldBinID))
}

// HasPicklist applies the HasEdge predicate on the "picklist" edge.
func HasPicklist() predicate.PickTask {
	return predicate.PickTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PicklistTable, PicklistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPicklistWith applies the HasEdge predicate on the "picklist" edge with a given conditions (other predicates).
func HasPicklistWith(preds ...predicate.PickList) predicate.PickTask {
	return predicate.PickTask(func(s *sql.Selector) {
		step := newPicklistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrderLine applies the HasEdge predicate on the "order_line" edge.
func HasOrderLine() predicate.PickTask {
	return predicate.PickTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderLineTable, OrderLineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderLineWith applies the HasEdge predicate on the "order_line" edge with a given conditions (other predicates).
func HasOrderLineWith(preds ...predicate.OrderLine) predicate.PickTask {
	return predicate.PickTask(func(s *sql.Selector) {
		step := newOrderLineStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PickTask) predicate.PickTask {
	return predicate.PickTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PickTask) predicate.PickTask {
	return predicate.PickTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PickTask) predicate.PickTask {
	return predicate.PickTask(sql.NotPredicates(p))
}
