// Code generated by ent, DO NOT EDIT.

package tracking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tracking type in the database.
	Label = "tracking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackingID holds the string denoting the tracking_id field in the database.
	FieldTrackingID = "tracking_id"
	// FieldTrackingURL holds the string denoting the tracking_url field in the database.
	FieldTrackingURL = "tracking_url"
	// FieldCarrier holds the string denoting the carrier field in the database.
	FieldCarrier = "carrier"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// Table holds the table name of the tracking in the database.
	Table = "trackings"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "trackings"
	// OrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderInverseTable = "orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_tracking"
)

// Columns holds all SQL columns for tracking fields.
var Columns = []string{
	FieldID,
	FieldTrackingID,
	FieldTrackingURL,
	FieldCarrier,
	FieldCreatedAt,
	FieldUpdateAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "trackings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"order_tracking",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TrackingIDValidator is a validator for the "tracking_id" field. It is called by the builders before save.
	TrackingIDValidator func(string) error
	// DefaultTrackingURL holds the default value on creation for the "tracking_url" field.
	DefaultTrackingURL string
	// DefaultCarrier holds the default value on creation for the "carrier" field.
	DefaultCarrier string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() time.Time
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() time.Time
)

// OrderOption defines the ordering options for the Tracking queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackingID orders the results by the tracking_id field.
func ByTrackingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackingID, opts...).ToFunc()
}

// ByTrackingURL orders the results by the tracking_url field.
func ByTrackingURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackingURL, opts...).ToFunc()
}

// ByCarrier orders the results by the carrier field.
func ByCarrier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCarrier, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdateAt orders the results by the update_at field.
func ByUpdateAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateAt, opts...).ToFunc()
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
	)
}
