// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/wms/ent/auditevent"
)

// AuditEvent is the model entity for the AuditEvent schema.
type AuditEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts time.Time `json:"ts,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Entity holds the value of the "entity" field.
	Entity string `json:"entity,omitempty"`
	// EntityRef holds the value of the "entity_ref" field.
	EntityRef string `json:"entity_ref,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor string `json:"actor,omitempty"`
	// Details holds the value of the "details" field.
	Details      string `json:"details,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			values[i] = new(sql.NullInt64)
		case auditevent.FieldAction, auditevent.FieldEntity, auditevent.FieldEntityRef, auditevent.FieldActor, auditevent.FieldDetails:
			values[i] = new(sql.NullString)
		case auditevent.FieldTs:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditEvent fields.
func (_m *AuditEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case auditevent.FieldTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Time
			}
		case auditevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case auditevent.FieldEntity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity", values[i])
			} else if value.Valid {
				_m.Entity = value.String
			}
		case auditevent.FieldEntityRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_ref", values[i])
			} else if value.Valid {
				_m.EntityRef = value.String
			}
		case auditevent.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = value.String
			}
		case auditevent.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AuditEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditEvent.
// Note that you need to call AuditEvent.Unwrap() before calling this method if this AuditEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditEvent) Update() *AuditEventUpdateOne {
	return NewAuditEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditEvent) Unwrap() *AuditEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AuditEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts=")
	builder.WriteString(_m.Ts.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("entity=")
	builder.WriteString(_m.Entity)
	builder.WriteString(", ")
	builder.WriteString("entity_ref=")
	builder.WriteString(_m.EntityRef)
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(_m.Actor)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(_m.Details)
	builder.WriteByte(')')
	return builder.String()
}

// AuditEvents is a parsable slice of AuditEvent.
type AuditEvents []*AuditEvent
