// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/wms/ent/bin"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/zone"
)

// Bin is the model entity for the Bin schema.
type Bin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BinQuery when eager-loading is set.
	Edges         BinEdges `json:"edges"`
	location_bins *int
	zone_bins     *int
	selectValues  sql.SelectValues
}

// BinEdges holds the relations/edges for other nodes in the graph.
type BinEdges struct {
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// Zone holds the value of the zone edge.
	Zone *Zone `json:"zone,omitempty"`
	// Items holds the value of the items edge.
	Items []*Item `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BinEdges) LocationOrErr() (*Location, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: location.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// ZoneOrErr returns the Zone value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BinEdges) ZoneOrErr() (*Zone, error) {
	if e.Zone != nil {
		return e.Zone, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: zone.Label}
	}
	return nil, &NotLoadedError{edge: "zone"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e BinEdges) ItemsOrErr() ([]*Item, error) {
	if e.loadedTypes[2] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bin.FieldID:
			values[i] = new(sql.NullInt64)
		case bin.FieldCode, bin.FieldName:
			values[i] = new(sql.NullString)
		case bin.ForeignKeys[0]: // location_bins
			values[i] = new(sql.NullInt64)
		case bin.ForeignKeys[1]: // zone_bins
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bin fields.
func (_m *Bin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bin.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case bin.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field location_bins", value)
			} else if value.Valid {
				_m.location_bins = new(int)
				*_m.location_bins = int(value.Int64)
			}
		case bin.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field zone_bins", value)
			} else if value.Valid {
				_m.zone_bins = new(int)
				*_m.zone_bins = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bin.
// This includes values selected through modifiers, order, etc.
func (_m *Bin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLocation queries the "location" edge of the Bin entity.
func (_m *Bin) QueryLocation() *LocationQuery {
	return NewBinClient(_m.config).QueryLocation(_m)
}

// QueryZone queries the "zone" edge of the Bin entity.
func (_m *Bin) QueryZone() *ZoneQuery {
	return NewBinClient(_m.config).QueryZone(_m)
}

// QueryItems queries the "items" edge of the Bin entity.
func (_m *Bin) QueryItems() *ItemQuery {
	return NewBinClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Bin.
// Note that you need to call Bin.Unwrap() before calling this method if this Bin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Bin) Update() *BinUpdateOne {
	return NewBinClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Bin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Bin) Unwrap() *Bin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Bin) String() string {
	var builder strings.Builder
	builder.WriteString("Bin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Bins is a parsable slice of Bin.
type Bins []*Bin
