// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/bin"
	"github.com/mxV03/wms/ent/item"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/zone"
)

// BinCreate is the builder for creating a Bin entity.
type BinCreate struct {
	config
	mutation *BinMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *BinCreate) SetCode(v string) *BinCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BinCreate) SetName(v string) *BinCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *BinCreate) SetNillableName(v *string) *BinCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (_c *BinCreate) SetLocationID(id int) *BinCreate {
	_c.mutation.SetLocationID(id)
	return _c
}

// SetLocation sets the "location" edge to the Location entity.
func (_c *BinCreate) SetLocation(v *Location) *BinCreate {
	return _c.SetLocationID(v.ID)
}

// SetZoneID sets the "zone" edge to the Zone entity by ID.
func (_c *BinCreate) SetZoneID(id int) *BinCreate {
	_c.mutation.SetZoneID(id)
	return _c
}

// SetZone sets the "zone" edge to the Zone entity.
func (_c *BinCreate) SetZone(v *Zone) *BinCreate {
	return _c.SetZoneID(v.ID)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_c *BinCreate) AddItemIDs(ids ...int) *BinCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the Item entity.
func (_c *BinCreate) AddItems(v ...*Item) *BinCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the BinMutation object of the builder.
func (_c *BinCreate) Mutation() *BinMutation {
	return _c.mutation
}

// Save creates the Bin in the database.
func (_c *BinCreate) Save(ctx context.Context) (*Bin, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BinCreate) SaveX(ctx context.Context) *Bin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BinCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Bin.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := bin.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Bin.code": %w`, err)}
		}
	}
	if len(_c.mutation.LocationIDs()) == 0 {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required edge "Bin.location"`)}
	}
	if len(_c.mutation.ZoneIDs()) == 0 {
		return &ValidationError{Name: "zone", err: errors.New(`ent: missing required edge "Bin.zone"`)}
	}
	return nil
}

func (_c *BinCreate) sqlSave(ctx context.Context) (*Bin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BinCreate) createSpec() (*Bin, *sqlgraph.CreateSpec) {
	var (
		_node = &Bin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bin.Table, sqlgraph.NewFieldSpec(bin.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(bin.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bin.LocationTable,
			Columns: []string{bin.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.location_bins = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ZoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bin.ZoneTable,
			Columns: []string{bin.ZoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(zone.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.zone_bins = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bin.ItemsTable,
			Columns: bin.ItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BinCreateBulk is the builder for creating many Bin entities in bulk.
type BinCreateBulk struct {
	config
	err      error
	builders []*BinCreate
}

// Save creates the Bin entities in the database.
func (_c *BinCreateBulk) Save(ctx context.Context) ([]*Bin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BinCreateBulk) SaveX(ctx context.Context) []*Bin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
