// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/mxV03/wms/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mxV03/wms/ent/bin"
	"github.com/mxV03/wms/ent/item"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/picktask"
	"github.com/mxV03/wms/ent/stockmovement"
	"github.com/mxV03/wms/ent/tracking"
	"github.com/mxV03/wms/ent/zone"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Bin is the client for interacting with the Bin builders.
	Bin *BinClient
	// Item is the client for interacting with the Item builders.
	Item *ItemClient
	// Location is the client for interacting with the Location builders.
	Location *LocationClient
	// Order is the client for interacting with the Order builders.
	Order *OrderClient
	// OrderLine is the client for interacting with the OrderLine builders.
	OrderLine *OrderLineClient
	// PickList is the client for interacting with the PickList builders.
	PickList *PickListClient
	// PickTask is the client for interacting with the PickTask builders.
	PickTask *PickTaskClient
	// StockMovement is the client for interacting with the StockMovement builders.
	StockMovement *StockMovementClient
	// Tracking is the client for interacting with the Tracking builders.
	Tracking *TrackingClient
	// Zone is the client for interacting with the Zone builders.
	Zone *ZoneClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Bin = NewBinClient(c.config)
	c.Item = NewItemClient(c.config)
	c.Location = NewLocationClient(c.config)
	c.Order = NewOrderClient(c.config)
	c.OrderLine = NewOrderLineClient(c.config)
	c.PickList = NewPickListClient(c.config)
	c.PickTask = NewPickTaskClient(c.config)
	c.StockMovement = NewStockMovementClient(c.config)
	c.Tracking = NewTrackingClient(c.config)
	c.Zone = NewZoneClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Bin:           NewBinClient(cfg),
		Item:          NewItemClient(cfg),
		Location:      NewLocationClient(cfg),
		Order:         NewOrderClient(cfg),
		OrderLine:     NewOrderLineClient(cfg),
		PickList:      NewPickListClient(cfg),
		PickTask:      NewPickTaskClient(cfg),
		StockMovement: NewStockMovementClient(cfg),
		Tracking:      NewTrackingClient(cfg),
		Zone:          NewZoneClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Bin:           NewBinClient(cfg),
		Item:          NewItemClient(cfg),
		Location:      NewLocationClient(cfg),
		Order:         NewOrderClient(cfg),
		OrderLine:     NewOrderLineClient(cfg),
		PickList:      NewPickListClient(cfg),
		PickTask:      NewPickTaskClient(cfg),
		StockMovement: NewStockMovementClient(cfg),
		Tracking:      NewTrackingClient(cfg),
		Zone:          NewZoneClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Bin.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Bin, c.Item, c.Location, c.Order, c.OrderLine, c.PickList, c.PickTask,
		c.StockMovement, c.Tracking, c.Zone,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Bin, c.Item, c.Location, c.Order, c.OrderLine, c.PickList, c.PickTask,
		c.StockMovement, c.Tracking, c.Zone,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BinMutation:
		return c.Bin.mutate(ctx, m)
	case *ItemMutation:
		return c.Item.mutate(ctx, m)
	case *LocationMutation:
		return c.Location.mutate(ctx, m)
	case *OrderMutation:
		return c.Order.mutate(ctx, m)
	case *OrderLineMutation:
		return c.OrderLine.mutate(ctx, m)
	case *PickListMutation:
		return c.PickList.mutate(ctx, m)
	case *PickTaskMutation:
		return c.PickTask.mutate(ctx, m)
	case *StockMovementMutation:
		return c.StockMovement.mutate(ctx, m)
	case *TrackingMutation:
		return c.Tracking.mutate(ctx, m)
	case *ZoneMutation:
		return c.Zone.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BinClient is a client for the Bin schema.
type BinClient struct {
	config
}

// NewBinClient returns a client for the Bin from the given config.
func NewBinClient(c config) *BinClient {
	return &BinClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bin.Hooks(f(g(h())))`.
func (c *BinClient) Use(hooks ...Hook) {
	c.hooks.Bin = append(c.hooks.Bin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bin.Intercept(f(g(h())))`.
func (c *BinClient) Intercept(interceptors ...Interceptor) {
	c.inters.Bin = append(c.inters.Bin, interceptors...)
}

// Create returns a builder for creating a Bin entity.
func (c *BinClient) Create() *BinCreate {
	mutation := newBinMutation(c.config, OpCreate)
	return &BinCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bin entities.
func (c *BinClient) CreateBulk(builders ...*BinCreate) *BinCreateBulk {
	return &BinCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BinClient) MapCreateBulk(slice any, setFunc func(*BinCreate, int)) *BinCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BinCreateBulk{err: fmt.Errorf("calling to BinClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BinCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BinCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bin.
func (c *BinClient) Update() *BinUpdate {
	mutation := newBinMutation(c.config, OpUpdate)
	return &BinUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BinClient) UpdateOne(_m *Bin) *BinUpdateOne {
	mutation := newBinMutation(c.config, OpUpdateOne, withBin(_m))
	return &BinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BinClient) UpdateOneID(id int) *BinUpdateOne {
	mutation := newBinMutation(c.config, OpUpdateOne, withBinID(id))
	return &BinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bin.
func (c *BinClient) Delete() *BinDelete {
	mutation := newBinMutation(c.config, OpDelete)
	return &BinDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BinClient) DeleteOne(_m *Bin) *BinDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BinClient) DeleteOneID(id int) *BinDeleteOne {
	builder := c.Delete().Where(bin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BinDeleteOne{builder}
}

// Query returns a query builder for Bin.
func (c *BinClient) Query() *BinQuery {
	return &BinQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBin},
		inters: c.Interceptors(),
	}
}

// Get returns a Bin entity by its id.
func (c *BinClient) Get(ctx context.Context, id int) (*Bin, error) {
	return c.Query().Where(bin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BinClient) GetX(ctx context.Context, id int) *Bin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLocation queries the location edge of a Bin.
func (c *BinClient) QueryLocation(_m *Bin) *LocationQuery {
	query := (&LocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bin.Table, bin.FieldID, id),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bin.LocationTable, bin.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryZone queries the zone edge of a Bin.
func (c *BinClient) QueryZone(_m *Bin) *ZoneQuery {
	query := (&ZoneClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bin.Table, bin.FieldID, id),
			sqlgraph.To(zone.Table, zone.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bin.ZoneTable, bin.ZoneColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItems queries the items edge of a Bin.
func (c *BinClient) QueryItems(_m *Bin) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bin.Table, bin.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bin.ItemsTable, bin.ItemsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BinClient) Hooks() []Hook {
	return c.hooks.Bin
}

// Interceptors returns the client interceptors.
func (c *BinClient) Interceptors() []Interceptor {
	return c.inters.Bin
}

func (c *BinClient) mutate(ctx context.Context, m *BinMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BinCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BinUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BinDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Bin mutation op: %q", m.Op())
	}
}

// ItemClient is a client for the Item schema.
type ItemClient struct {
	config
}

// NewItemClient returns a client for the Item from the given config.
func NewItemClient(c config) *ItemClient {
	return &ItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `item.Hooks(f(g(h())))`.
func (c *ItemClient) Use(hooks ...Hook) {
	c.hooks.Item = append(c.hooks.Item, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `item.Intercept(f(g(h())))`.
func (c *ItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.Item = append(c.inters.Item, interceptors...)
}

// Create returns a builder for creating a Item entity.
func (c *ItemClient) Create() *ItemCreate {
	mutation := newItemMutation(c.config, OpCreate)
	return &ItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Item entities.
func (c *ItemClient) CreateBulk(builders ...*ItemCreate) *ItemCreateBulk {
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ItemClient) MapCreateBulk(slice any, setFunc func(*ItemCreate, int)) *ItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ItemCreateBulk{err: fmt.Errorf("calling to ItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Item.
func (c *ItemClient) Update() *ItemUpdate {
	mutation := newItemMutation(c.config, OpUpdate)
	return &ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemClient) UpdateOne(_m *Item) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItem(_m))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemClient) UpdateOneID(id int) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItemID(id))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Item.
func (c *ItemClient) Delete() *ItemDelete {
	mutation := newItemMutation(c.config, OpDelete)
	return &ItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ItemClient) DeleteOne(_m *Item) *ItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ItemClient) DeleteOneID(id int) *ItemDeleteOne {
	builder := c.Delete().Where(item.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemDeleteOne{builder}
}

// Query returns a query builder for Item.
func (c *ItemClient) Query() *ItemQuery {
	return &ItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeItem},
		inters: c.Interceptors(),
	}
}

// Get returns a Item entity by its id.
func (c *ItemClient) Get(ctx context.Context, id int) (*Item, error) {
	return c.Query().Where(item.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemClient) GetX(ctx context.Context, id int) *Item {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovements queries the movements edge of a Item.
func (c *ItemClient) QueryMovements(_m *Item) *StockMovementQuery {
	query := (&StockMovementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(stockmovement.Table, stockmovement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.MovementsTable, item.MovementsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrderLines queries the order_lines edge of a Item.
func (c *ItemClient) QueryOrderLines(_m *Item) *OrderLineQuery {
	query := (&OrderLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(orderline.Table, orderline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.OrderLinesTable, item.OrderLinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBins queries the bins edge of a Item.
func (c *ItemClient) QueryBins(_m *Item) *BinQuery {
	query := (&BinClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(bin.Table, bin.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, item.BinsTable, item.BinsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ItemClient) Hooks() []Hook {
	return c.hooks.Item
}

// Interceptors returns the client interceptors.
func (c *ItemClient) Interceptors() []Interceptor {
	return c.inters.Item
}

func (c *ItemClient) mutate(ctx context.Context, m *ItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Item mutation op: %q", m.Op())
	}
}

// LocationClient is a client for the Location schema.
type LocationClient struct {
	config
}

// NewLocationClient returns a client for the Location from the given config.
func NewLocationClient(c config) *LocationClient {
	return &LocationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `location.Hooks(f(g(h())))`.
func (c *LocationClient) Use(hooks ...Hook) {
	c.hooks.Location = append(c.hooks.Location, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `location.Intercept(f(g(h())))`.
func (c *LocationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Location = append(c.inters.Location, interceptors...)
}

// Create returns a builder for creating a Location entity.
func (c *LocationClient) Create() *LocationCreate {
	mutation := newLocationMutation(c.config, OpCreate)
	return &LocationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Location entities.
func (c *LocationClient) CreateBulk(builders ...*LocationCreate) *LocationCreateBulk {
	return &LocationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LocationClient) MapCreateBulk(slice any, setFunc func(*LocationCreate, int)) *LocationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LocationCreateBulk{err: fmt.Errorf("calling to LocationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LocationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LocationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Location.
func (c *LocationClient) Update() *LocationUpdate {
	mutation := newLocationMutation(c.config, OpUpdate)
	return &LocationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LocationClient) UpdateOne(_m *Location) *LocationUpdateOne {
	mutation := newLocationMutation(c.config, OpUpdateOne, withLocation(_m))
	return &LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LocationClient) UpdateOneID(id int) *LocationUpdateOne {
	mutation := newLocationMutation(c.config, OpUpdateOne, withLocationID(id))
	return &LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Location.
func (c *LocationClient) Delete() *LocationDelete {
	mutation := newLocationMutation(c.config, OpDelete)
	return &LocationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LocationClient) DeleteOne(_m *Location) *LocationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LocationClient) DeleteOneID(id int) *LocationDeleteOne {
	builder := c.Delete().Where(location.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LocationDeleteOne{builder}
}

// Query returns a query builder for Location.
func (c *LocationClient) Query() *LocationQuery {
	return &LocationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLocation},
		inters: c.Interceptors(),
	}
}

// Get returns a Location entity by its id.
func (c *LocationClient) Get(ctx context.Context, id int) (*Location, error) {
	return c.Query().Where(location.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LocationClient) GetX(ctx context.Context, id int) *Location {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovements queries the movements edge of a Location.
func (c *LocationClient) QueryMovements(_m *Location) *StockMovementQuery {
	query := (&StockMovementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(location.Table, location.FieldID, id),
			sqlgraph.To(stockmovement.Table, stockmovement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, location.MovementsTable, location.MovementsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrderLines queries the order_lines edge of a Location.
func (c *LocationClient) QueryOrderLines(_m *Location) *OrderLineQuery {
	query := (&OrderLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(location.Table, location.FieldID, id),
			sqlgraph.To(orderline.Table, orderline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, location.OrderLinesTable, location.OrderLinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryZones queries the zones edge of a Location.
func (c *LocationClient) QueryZones(_m *Location) *ZoneQuery {
	query := (&ZoneClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(location.Table, location.FieldID, id),
			sqlgraph.To(zone.Table, zone.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, location.ZonesTable, location.ZonesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBins queries the bins edge of a Location.
func (c *LocationClient) QueryBins(_m *Location) *BinQuery {
	query := (&BinClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(location.Table, location.FieldID, id),
			sqlgraph.To(bin.Table, bin.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, location.BinsTable, location.BinsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LocationClient) Hooks() []Hook {
	return c.hooks.Location
}

// Interceptors returns the client interceptors.
func (c *LocationClient) Interceptors() []Interceptor {
	return c.inters.Location
}

func (c *LocationClient) mutate(ctx context.Context, m *LocationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LocationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LocationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LocationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Location mutation op: %q", m.Op())
	}
}

// OrderClient is a client for the Order schema.
type OrderClient struct {
	config
}

// NewOrderClient returns a client for the Order from the given config.
func NewOrderClient(c config) *OrderClient {
	return &OrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `order.Hooks(f(g(h())))`.
func (c *OrderClient) Use(hooks ...Hook) {
	c.hooks.Order = append(c.hooks.Order, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `order.Intercept(f(g(h())))`.
func (c *OrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.Order = append(c.inters.Order, interceptors...)
}

// Create returns a builder for creating a Order entity.
func (c *OrderClient) Create() *OrderCreate {
	mutation := newOrderMutation(c.config, OpCreate)
	return &OrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Order entities.
func (c *OrderClient) CreateBulk(builders ...*OrderCreate) *OrderCreateBulk {
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderClient) MapCreateBulk(slice any, setFunc func(*OrderCreate, int)) *OrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderCreateBulk{err: fmt.Errorf("calling to OrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Order.
func (c *OrderClient) Update() *OrderUpdate {
	mutation := newOrderMutation(c.config, OpUpdate)
	return &OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderClient) UpdateOne(_m *Order) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrder(_m))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderClient) UpdateOneID(id int) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrderID(id))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Order.
func (c *OrderClient) Delete() *OrderDelete {
	mutation := newOrderMutation(c.config, OpDelete)
	return &OrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderClient) DeleteOne(_m *Order) *OrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderClient) DeleteOneID(id int) *OrderDeleteOne {
	builder := c.Delete().Where(order.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderDeleteOne{builder}
}

// Query returns a query builder for Order.
func (c *OrderClient) Query() *OrderQuery {
	return &OrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a Order entity by its id.
func (c *OrderClient) Get(ctx context.Context, id int) (*Order, error) {
	return c.Query().Where(order.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderClient) GetX(ctx context.Context, id int) *Order {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLines queries the lines edge of a Order.
func (c *OrderClient) QueryLines(_m *Order) *OrderLineQuery {
	query := (&OrderLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, id),
			sqlgraph.To(orderline.Table, orderline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.LinesTable, order.LinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPicklist queries the picklist edge of a Order.
func (c *OrderClient) QueryPicklist(_m *Order) *PickListQuery {
	query := (&PickListClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, id),
			sqlgraph.To(picklist.Table, picklist.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, order.PicklistTable, order.PicklistColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTracking queries the tracking edge of a Order.
func (c *OrderClient) QueryTracking(_m *Order) *TrackingQuery {
	query := (&TrackingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, id),
			sqlgraph.To(tracking.Table, tracking.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, order.TrackingTable, order.TrackingColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderClient) Hooks() []Hook {
	return c.hooks.Order
}

// Interceptors returns the client interceptors.
func (c *OrderClient) Interceptors() []Interceptor {
	return c.inters.Order
}

func (c *OrderClient) mutate(ctx context.Context, m *OrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Order mutation op: %q", m.Op())
	}
}

// OrderLineClient is a client for the OrderLine schema.
type OrderLineClient struct {
	config
}

// NewOrderLineClient returns a client for the OrderLine from the given config.
func NewOrderLineClient(c config) *OrderLineClient {
	return &OrderLineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `orderline.Hooks(f(g(h())))`.
func (c *OrderLineClient) Use(hooks ...Hook) {
	c.hooks.OrderLine = append(c.hooks.OrderLine, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `orderline.Intercept(f(g(h())))`.
func (c *OrderLineClient) Intercept(interceptors ...Interceptor) {
	c.inters.OrderLine = append(c.inters.OrderLine, interceptors...)
}

// Create returns a builder for creating a OrderLine entity.
func (c *OrderLineClient) Create() *OrderLineCreate {
	mutation := newOrderLineMutation(c.config, OpCreate)
	return &OrderLineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OrderLine entities.
func (c *OrderLineClient) CreateBulk(builders ...*OrderLineCreate) *OrderLineCreateBulk {
	return &OrderLineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderLineClient) MapCreateBulk(slice any, setFunc func(*OrderLineCreate, int)) *OrderLineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderLineCreateBulk{err: fmt.Errorf("calling to OrderLineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderLineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderLineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OrderLine.
func (c *OrderLineClient) Update() *OrderLineUpdate {
	mutation := newOrderLineMutation(c.config, OpUpdate)
	return &OrderLineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderLineClient) UpdateOne(_m *OrderLine) *OrderLineUpdateOne {
	mutation := newOrderLineMutation(c.config, OpUpdateOne, withOrderLine(_m))
	return &OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderLineClient) UpdateOneID(id int) *OrderLineUpdateOne {
	mutation := newOrderLineMutation(c.config, OpUpdateOne, withOrderLineID(id))
	return &OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OrderLine.
func (c *OrderLineClient) Delete() *OrderLineDelete {
	mutation := newOrderLineMutation(c.config, OpDelete)
	return &OrderLineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderLineClient) DeleteOne(_m *OrderLine) *OrderLineDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderLineClient) DeleteOneID(id int) *OrderLineDeleteOne {
	builder := c.Delete().Where(orderline.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderLineDeleteOne{builder}
}

// Query returns a query builder for OrderLine.
func (c *OrderLineClient) Query() *OrderLineQuery {
	return &OrderLineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrderLine},
		inters: c.Interceptors(),
	}
}

// Get returns a OrderLine entity by its id.
func (c *OrderLineClient) Get(ctx context.Context, id int) (*OrderLine, error) {
	return c.Query().Where(orderline.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderLineClient) GetX(ctx context.Context, id int) *OrderLine {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrder queries the order edge of a OrderLine.
func (c *OrderLineClient) QueryOrder(_m *OrderLine) *OrderQuery {
	query := (&OrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, id),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.OrderTable, orderline.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItem queries the item edge of a OrderLine.
func (c *OrderLineClient) QueryItem(_m *OrderLine) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.ItemTable, orderline.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLocation queries the location edge of a OrderLine.
func (c *OrderLineClient) QueryLocation(_m *OrderLine) *LocationQuery {
	query := (&LocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, id),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.LocationTable, orderline.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPickTasks queries the pick_tasks edge of a OrderLine.
func (c *OrderLineClient) QueryPickTasks(_m *OrderLine) *PickTaskQuery {
	query := (&PickTaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, id),
			sqlgraph.To(picktask.Table, picktask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, orderline.PickTasksTable, orderline.PickTasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderLineClient) Hooks() []Hook {
	return c.hooks.OrderLine
}

// Interceptors returns the client interceptors.
func (c *OrderLineClient) Interceptors() []Interceptor {
	return c.inters.OrderLine
}

func (c *OrderLineClient) mutate(ctx context.Context, m *OrderLineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderLineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderLineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderLineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OrderLine mutation op: %q", m.Op())
	}
}

// PickListClient is a client for the PickList schema.
type PickListClient struct {
	config
}

// NewPickListClient returns a client for the PickList from the given config.
func NewPickListClient(c config) *PickListClient {
	return &PickListClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `picklist.Hooks(f(g(h())))`.
func (c *PickListClient) Use(hooks ...Hook) {
	c.hooks.PickList = append(c.hooks.PickList, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `picklist.Intercept(f(g(h())))`.
func (c *PickListClient) Intercept(interceptors ...Interceptor) {
	c.inters.PickList = append(c.inters.PickList, interceptors...)
}

// Create returns a builder for creating a PickList entity.
func (c *PickListClient) Create() *PickListCreate {
	mutation := newPickListMutation(c.config, OpCreate)
	return &PickListCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PickList entities.
func (c *PickListClient) CreateBulk(builders ...*PickListCreate) *PickListCreateBulk {
	return &PickListCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PickListClient) MapCreateBulk(slice any, setFunc func(*PickListCreate, int)) *PickListCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PickListCreateBulk{err: fmt.Errorf("calling to PickListClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PickListCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PickListCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PickList.
func (c *PickListClient) Update() *PickListUpdate {
	mutation := newPickListMutation(c.config, OpUpdate)
	return &PickListUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PickListClient) UpdateOne(_m *PickList) *PickListUpdateOne {
	mutation := newPickListMutation(c.config, OpUpdateOne, withPickList(_m))
	return &PickListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PickListClient) UpdateOneID(id int) *PickListUpdateOne {
	mutation := newPickListMutation(c.config, OpUpdateOne, withPickListID(id))
	return &PickListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PickList.
func (c *PickListClient) Delete() *PickListDelete {
	mutation := newPickListMutation(c.config, OpDelete)
	return &PickListDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PickListClient) DeleteOne(_m *PickList) *PickListDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PickListClient) DeleteOneID(id int) *PickListDeleteOne {
	builder := c.Delete().Where(picklist.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PickListDeleteOne{builder}
}

// Query returns a query builder for PickList.
func (c *PickListClient) Query() *PickListQuery {
	return &PickListQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePickList},
		inters: c.Interceptors(),
	}
}

// Get returns a PickList entity by its id.
func (c *PickListClient) Get(ctx context.Context, id int) (*PickList, error) {
	return c.Query().Where(picklist.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PickListClient) GetX(ctx context.Context, id int) *PickList {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrder queries the order edge of a PickList.
func (c *PickListClient) QueryOrder(_m *PickList) *OrderQuery {
	query := (&OrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(picklist.Table, picklist.FieldID, id),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, picklist.OrderTable, picklist.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTasks queries the tasks edge of a PickList.
func (c *PickListClient) QueryTasks(_m *PickList) *PickTaskQuery {
	query := (&PickTaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(picklist.Table, picklist.FieldID, id),
			sqlgraph.To(picktask.Table, picktask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, picklist.TasksTable, picklist.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PickListClient) Hooks() []Hook {
	return c.hooks.PickList
}

// Interceptors returns the client interceptors.
func (c *PickListClient) Interceptors() []Interceptor {
	return c.inters.PickList
}

func (c *PickListClient) mutate(ctx context.Context, m *PickListMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PickListCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PickListUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PickListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PickListDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PickList mutation op: %q", m.Op())
	}
}

// PickTaskClient is a client for the PickTask schema.
type PickTaskClient struct {
	config
}

// NewPickTaskClient returns a client for the PickTask from the given config.
func NewPickTaskClient(c config) *PickTaskClient {
	return &PickTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `picktask.Hooks(f(g(h())))`.
func (c *PickTaskClient) Use(hooks ...Hook) {
	c.hooks.PickTask = append(c.hooks.PickTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `picktask.Intercept(f(g(h())))`.
func (c *PickTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.PickTask = append(c.inters.PickTask, interceptors...)
}

// Create returns a builder for creating a PickTask entity.
func (c *PickTaskClient) Create() *PickTaskCreate {
	mutation := newPickTaskMutation(c.config, OpCreate)
	return &PickTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PickTask entities.
func (c *PickTaskClient) CreateBulk(builders ...*PickTaskCreate) *PickTaskCreateBulk {
	return &PickTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PickTaskClient) MapCreateBulk(slice any, setFunc func(*PickTaskCreate, int)) *PickTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PickTaskCreateBulk{err: fmt.Errorf("calling to PickTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PickTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PickTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PickTask.
func (c *PickTaskClient) Update() *PickTaskUpdate {
	mutation := newPickTaskMutation(c.config, OpUpdate)
	return &PickTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PickTaskClient) UpdateOne(_m *PickTask) *PickTaskUpdateOne {
	mutation := newPickTaskMutation(c.config, OpUpdateOne, withPickTask(_m))
	return &PickTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PickTaskClient) UpdateOneID(id int) *PickTaskUpdateOne {
	mutation := newPickTaskMutation(c.config, OpUpdateOne, withPickTaskID(id))
	return &PickTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PickTask.
func (c *PickTaskClient) Delete() *PickTaskDelete {
	mutation := newPickTaskMutation(c.config, OpDelete)
	return &PickTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PickTaskClient) DeleteOne(_m *PickTask) *PickTaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PickTaskClient) DeleteOneID(id int) *PickTaskDeleteOne {
	builder := c.Delete().Where(picktask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PickTaskDeleteOne{builder}
}

// Query returns a query builder for PickTask.
func (c *PickTaskClient) Query() *PickTaskQuery {
	return &PickTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePickTask},
		inters: c.Interceptors(),
	}
}

// Get returns a PickTask entity by its id.
func (c *PickTaskClient) Get(ctx context.Context, id int) (*PickTask, error) {
	return c.Query().Where(picktask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PickTaskClient) GetX(ctx context.Context, id int) *PickTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPicklist queries the picklist edge of a PickTask.
func (c *PickTaskClient) QueryPicklist(_m *PickTask) *PickListQuery {
	query := (&PickListClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(picktask.Table, picktask.FieldID, id),
			sqlgraph.To(picklist.Table, picklist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, picktask.PicklistTable, picktask.PicklistColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrderLine queries the order_line edge of a PickTask.
func (c *PickTaskClient) QueryOrderLine(_m *PickTask) *OrderLineQuery {
	query := (&OrderLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(picktask.Table, picktask.FieldID, id),
			sqlgraph.To(orderline.Table, orderline.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, picktask.OrderLineTable, picktask.OrderLineColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PickTaskClient) Hooks() []Hook {
	return c.hooks.PickTask
}

// Interceptors returns the client interceptors.
func (c *PickTaskClient) Interceptors() []Interceptor {
	return c.inters.PickTask
}

func (c *PickTaskClient) mutate(ctx context.Context, m *PickTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PickTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PickTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PickTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PickTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PickTask mutation op: %q", m.Op())
	}
}

// StockMovementClient is a client for the StockMovement schema.
type StockMovementClient struct {
	config
}

// NewStockMovementClient returns a client for the StockMovement from the given config.
func NewStockMovementClient(c config) *StockMovementClient {
	return &StockMovementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stockmovement.Hooks(f(g(h())))`.
func (c *StockMovementClient) Use(hooks ...Hook) {
	c.hooks.StockMovement = append(c.hooks.StockMovement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stockmovement.Intercept(f(g(h())))`.
func (c *StockMovementClient) Intercept(interceptors ...Interceptor) {
	c.inters.StockMovement = append(c.inters.StockMovement, interceptors...)
}

// Create returns a builder for creating a StockMovement entity.
func (c *StockMovementClient) Create() *StockMovementCreate {
	mutation := newStockMovementMutation(c.config, OpCreate)
	return &StockMovementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StockMovement entities.
func (c *StockMovementClient) CreateBulk(builders ...*StockMovementCreate) *StockMovementCreateBulk {
	return &StockMovementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StockMovementClient) MapCreateBulk(slice any, setFunc func(*StockMovementCreate, int)) *StockMovementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StockMovementCreateBulk{err: fmt.Errorf("calling to StockMovementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StockMovementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StockMovementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StockMovement.
func (c *StockMovementClient) Update() *StockMovementUpdate {
	mutation := newStockMovementMutation(c.config, OpUpdate)
	return &StockMovementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StockMovementClient) UpdateOne(_m *StockMovement) *StockMovementUpdateOne {
	mutation := newStockMovementMutation(c.config, OpUpdateOne, withStockMovement(_m))
	return &StockMovementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StockMovementClient) UpdateOneID(id int) *StockMovementUpdateOne {
	mutation := newStockMovementMutation(c.config, OpUpdateOne, withStockMovementID(id))
	return &StockMovementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StockMovement.
func (c *StockMovementClient) Delete() *StockMovementDelete {
	mutation := newStockMovementMutation(c.config, OpDelete)
	return &StockMovementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StockMovementClient) DeleteOne(_m *StockMovement) *StockMovementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StockMovementClient) DeleteOneID(id int) *StockMovementDeleteOne {
	builder := c.Delete().Where(stockmovement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StockMovementDeleteOne{builder}
}

// Query returns a query builder for StockMovement.
func (c *StockMovementClient) Query() *StockMovementQuery {
	return &StockMovementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStockMovement},
		inters: c.Interceptors(),
	}
}

// Get returns a StockMovement entity by its id.
func (c *StockMovementClient) Get(ctx context.Context, id int) (*StockMovement, error) {
	return c.Query().Where(stockmovement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StockMovementClient) GetX(ctx context.Context, id int) *StockMovement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItem queries the item edge of a StockMovement.
func (c *StockMovementClient) QueryItem(_m *StockMovement) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stockmovement.Table, stockmovement.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockmovement.ItemTable, stockmovement.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLocation queries the location edge of a StockMovement.
func (c *StockMovementClient) QueryLocation(_m *StockMovement) *LocationQuery {
	query := (&LocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stockmovement.Table, stockmovement.FieldID, id),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockmovement.LocationTable, stockmovement.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StockMovementClient) Hooks() []Hook {
	return c.hooks.StockMovement
}

// Interceptors returns the client interceptors.
func (c *StockMovementClient) Interceptors() []Interceptor {
	return c.inters.StockMovement
}

func (c *StockMovementClient) mutate(ctx context.Context, m *StockMovementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StockMovementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StockMovementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StockMovementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StockMovementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StockMovement mutation op: %q", m.Op())
	}
}

// TrackingClient is a client for the Tracking schema.
type TrackingClient struct {
	config
}

// NewTrackingClient returns a client for the Tracking from the given config.
func NewTrackingClient(c config) *TrackingClient {
	return &TrackingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tracking.Hooks(f(g(h())))`.
func (c *TrackingClient) Use(hooks ...Hook) {
	c.hooks.Tracking = append(c.hooks.Tracking, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tracking.Intercept(f(g(h())))`.
func (c *TrackingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tracking = append(c.inters.Tracking, interceptors...)
}

// Create returns a builder for creating a Tracking entity.
func (c *TrackingClient) Create() *TrackingCreate {
	mutation := newTrackingMutation(c.config, OpCreate)
	return &TrackingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tracking entities.
func (c *TrackingClient) CreateBulk(builders ...*TrackingCreate) *TrackingCreateBulk {
	return &TrackingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TrackingClient) MapCreateBulk(slice any, setFunc func(*TrackingCreate, int)) *TrackingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TrackingCreateBulk{err: fmt.Errorf("calling to TrackingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TrackingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TrackingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tracking.
func (c *TrackingClient) Update() *TrackingUpdate {
	mutation := newTrackingMutation(c.config, OpUpdate)
	return &TrackingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TrackingClient) UpdateOne(_m *Tracking) *TrackingUpdateOne {
	mutation := newTrackingMutation(c.config, OpUpdateOne, withTracking(_m))
	return &TrackingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TrackingClient) UpdateOneID(id int) *TrackingUpdateOne {
	mutation := newTrackingMutation(c.config, OpUpdateOne, withTrackingID(id))
	return &TrackingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tracking.
func (c *TrackingClient) Delete() *TrackingDelete {
	mutation := newTrackingMutation(c.config, OpDelete)
	return &TrackingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TrackingClient) DeleteOne(_m *Tracking) *TrackingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TrackingClient) DeleteOneID(id int) *TrackingDeleteOne {
	builder := c.Delete().Where(tracking.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TrackingDeleteOne{builder}
}

// Query returns a query builder for Tracking.
func (c *TrackingClient) Query() *TrackingQuery {
	return &TrackingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTracking},
		inters: c.Interceptors(),
	}
}

// Get returns a Tracking entity by its id.
func (c *TrackingClient) Get(ctx context.Context, id int) (*Tracking, error) {
	return c.Query().Where(tracking.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TrackingClient) GetX(ctx context.Context, id int) *Tracking {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrder queries the order edge of a Tracking.
func (c *TrackingClient) QueryOrder(_m *Tracking) *OrderQuery {
	query := (&OrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tracking.Table, tracking.FieldID, id),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, tracking.OrderTable, tracking.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TrackingClient) Hooks() []Hook {
	return c.hooks.Tracking
}

// Interceptors returns the client interceptors.
func (c *TrackingClient) Interceptors() []Interceptor {
	return c.inters.Tracking
}

func (c *TrackingClient) mutate(ctx context.Context, m *TrackingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TrackingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TrackingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TrackingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TrackingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tracking mutation op: %q", m.Op())
	}
}

// ZoneClient is a client for the Zone schema.
type ZoneClient struct {
	config
}

// NewZoneClient returns a client for the Zone from the given config.
func NewZoneClient(c config) *ZoneClient {
	return &ZoneClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `zone.Hooks(f(g(h())))`.
func (c *ZoneClient) Use(hooks ...Hook) {
	c.hooks.Zone = append(c.hooks.Zone, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `zone.Intercept(f(g(h())))`.
func (c *ZoneClient) Intercept(interceptors ...Interceptor) {
	c.inters.Zone = append(c.inters.Zone, interceptors...)
}

// Create returns a builder for creating a Zone entity.
func (c *ZoneClient) Create() *ZoneCreate {
	mutation := newZoneMutation(c.config, OpCreate)
	return &ZoneCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Zone entities.
func (c *ZoneClient) CreateBulk(builders ...*ZoneCreate) *ZoneCreateBulk {
	return &ZoneCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ZoneClient) MapCreateBulk(slice any, setFunc func(*ZoneCreate, int)) *ZoneCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ZoneCreateBulk{err: fmt.Errorf("calling to ZoneClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ZoneCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ZoneCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Zone.
func (c *ZoneClient) Update() *ZoneUpdate {
	mutation := newZoneMutation(c.config, OpUpdate)
	return &ZoneUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ZoneClient) UpdateOne(_m *Zone) *ZoneUpdateOne {
	mutation := newZoneMutation(c.config, OpUpdateOne, withZone(_m))
	return &ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ZoneClient) UpdateOneID(id int) *ZoneUpdateOne {
	mutation := newZoneMutation(c.config, OpUpdateOne, withZoneID(id))
	return &ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Zone.
func (c *ZoneClient) Delete() *ZoneDelete {
	mutation := newZoneMutation(c.config, OpDelete)
	return &ZoneDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ZoneClient) DeleteOne(_m *Zone) *ZoneDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ZoneClient) DeleteOneID(id int) *ZoneDeleteOne {
	builder := c.Delete().Where(zone.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ZoneDeleteOne{builder}
}

// Query returns a query builder for Zone.
func (c *ZoneClient) Query() *ZoneQuery {
	return &ZoneQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeZone},
		inters: c.Interceptors(),
	}
}

// Get returns a Zone entity by its id.
func (c *ZoneClient) Get(ctx context.Context, id int) (*Zone, error) {
	return c.Query().Where(zone.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ZoneClient) GetX(ctx context.Context, id int) *Zone {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLocation queries the location edge of a Zone.
func (c *ZoneClient) QueryLocation(_m *Zone) *LocationQuery {
	query := (&LocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(zone.Table, zone.FieldID, id),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, zone.LocationTable, zone.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBins queries the bins edge of a Zone.
func (c *ZoneClient) QueryBins(_m *Zone) *BinQuery {
	query := (&BinClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(zone.Table, zone.FieldID, id),
			sqlgraph.To(bin.Table, bin.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, zone.BinsTable, zone.BinsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ZoneClient) Hooks() []Hook {
	return c.hooks.Zone
}

// Interceptors returns the client interceptors.
func (c *ZoneClient) Interceptors() []Interceptor {
	return c.inters.Zone
}

func (c *ZoneClient) mutate(ctx context.Context, m *ZoneMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ZoneCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ZoneUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ZoneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ZoneDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Zone mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Bin, Item, Location, Order, OrderLine, PickList, PickTask, StockMovement,
		Tracking, Zone []ent.Hook
	}
	inters struct {
		Bin, Item, Location, Order, OrderLine, PickList, PickTask, StockMovement,
		Tracking, Zone []ent.Interceptor
	}
)
