// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/item"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picktask"
	"github.com/mxV03/wms/ent/predicate"
)

// OrderLineQuery is the builder for querying OrderLine entities.
type OrderLineQuery struct {
	config
	ctx           *QueryContext
	order         []orderline.OrderOption
	inters        []Interceptor
	predicates    []predicate.OrderLine
	withOrder     *OrderQuery
	withItem      *ItemQuery
	withLocation  *LocationQuery
	withPickTasks *PickTaskQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderLineQuery builder.
func (_q *OrderLineQuery) Where(ps ...predicate.OrderLine) *OrderLineQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OrderLineQuery) Limit(limit int) *OrderLineQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OrderLineQuery) Offset(offset int) *OrderLineQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OrderLineQuery) Unique(unique bool) *OrderLineQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OrderLineQuery) Order(o ...orderline.OrderOption) *OrderLineQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrder chains the current query on the "order" edge.
func (_q *OrderLineQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.OrderTable, orderline.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItem chains the current query on the "item" edge.
func (_q *OrderLineQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.ItemTable, orderline.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocation chains the current query on the "location" edge.
func (_q *OrderLineQuery) QueryLocation() *LocationQuery {
	query := (&LocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, selector),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.LocationTable, orderline.LocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPickTasks chains the current query on the "pick_tasks" edge.
func (_q *OrderLineQuery) QueryPickTasks() *PickTaskQuery {
	query := (&PickTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, selector),
			sqlgraph.To(picktask.Table, picktask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, orderline.PickTasksTable, orderline.PickTasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrderLine entity from the query.
// Returns a *NotFoundError when no OrderLine was found.
func (_q *OrderLineQuery) First(ctx context.Context) (*OrderLine, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderline.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OrderLineQuery) FirstX(ctx context.Context) *OrderLine {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderLine ID from the query.
// Returns a *NotFoundError when no OrderLine ID was found.
func (_q *OrderLineQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderline.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OrderLineQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderLine entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderLine entity is found.
// Returns a *NotFoundError when no OrderLine entities are found.
func (_q *OrderLineQuery) Only(ctx context.Context) (*OrderLine, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderline.Label}
	default:
		return nil, &NotSingularError{orderline.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OrderLineQuery) OnlyX(ctx context.Context) *OrderLine {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderLine ID in the query.
// Returns a *NotSingularError when more than one OrderLine ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OrderLineQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderline.Label}
	default:
		err = &NotSingularError{orderline.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OrderLineQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderLines.
func (_q *OrderLineQuery) All(ctx context.Context) ([]*OrderLine, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderLine, *OrderLineQuery]()
	return withInterceptors[[]*OrderLine](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OrderLineQuery) AllX(ctx context.Context) []*OrderLine {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderLine IDs.
func (_q *OrderLineQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(orderline.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OrderLineQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OrderLineQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OrderLineQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OrderLineQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OrderLineQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OrderLineQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderLineQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OrderLineQuery) Clone() *OrderLineQuery {
	if _q == nil {
		return nil
	}
	return &OrderLineQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]orderline.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.OrderLine{}, _q.predicates...),
		withOrder:     _q.withOrder.Clone(),
		withItem:      _q.withItem.Clone(),
		withLocation:  _q.withLocation.Clone(),
		withPickTasks: _q.withPickTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderLineQuery) WithOrder(opts ...func(*OrderQuery)) *OrderLineQuery {
	query := (&OrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrder = query
	return _q
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderLineQuery) WithItem(opts ...func(*ItemQuery)) *OrderLineQuery {
	query := (&ItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withItem = query
	return _q
}

// WithLocation tells the query-builder to eager-load the nodes that are connected to
// the "location" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderLineQuery) WithLocation(opts ...func(*LocationQuery)) *OrderLineQuery {
	query := (&LocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocation = query
	return _q
}

// WithPickTasks tells the query-builder to eager-load the nodes that are connected to
// the "pick_tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderLineQuery) WithPickTasks(opts ...func(*PickTaskQuery)) *OrderLineQuery {
	query := (&PickTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPickTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderLine.Query().
//		GroupBy(orderline.FieldQuantity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OrderLineQuery) GroupBy(field string, fields ...string) *OrderLineGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderLineGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = orderline.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//	}
//
//	client.OrderLine.Query().
//		Select(orderline.FieldQuantity).
//		Scan(ctx, &v)
func (_q *OrderLineQuery) Select(fields ...string) *OrderLineSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OrderLineSelect{OrderLineQuery: _q}
	sbuild.label = orderline.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderLineSelect configured with the given aggregations.
func (_q *OrderLineQuery) Aggregate(fns ...AggregateFunc) *OrderLineSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OrderLineQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !orderline.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OrderLineQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderLine, error) {
	var (
		nodes       = []*OrderLine{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withOrder != nil,
			_q.withItem != nil,
			_q.withLocation != nil,
			_q.withPickTasks != nil,
		}
	)
	if _q.withOrder != nil || _q.withItem != nil || _q.withLocation != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, orderline.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderLine).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderLine{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrder; query != nil {
		if err := _q.loadOrder(ctx, query, nodes, nil,
			func(n *OrderLine, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withItem; query != nil {
		if err := _q.loadItem(ctx, query, nodes, nil,
			func(n *OrderLine, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocation; query != nil {
		if err := _q.loadLocation(ctx, query, nodes, nil,
			func(n *OrderLine, e *Location) { n.Edges.Location = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPickTasks; query != nil {
		if err := _q.loadPickTasks(ctx, query, nodes,
			func(n *OrderLine) { n.Edges.PickTasks = []*PickTask{} },
			func(n *OrderLine, e *PickTask) { n.Edges.PickTasks = append(n.Edges.PickTasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OrderLineQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*OrderLine, init func(*OrderLine), assign func(*OrderLine, *Order)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderLine)
	for i := range nodes {
		if nodes[i].order_lines == nil {
			continue
		}
		fk := *nodes[i].order_lines
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_lines" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderLineQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*OrderLine, init func(*OrderLine), assign func(*OrderLine, *Item)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderLine)
	for i := range nodes {
		if nodes[i].item_order_lines == nil {
			continue
		}
		fk := *nodes[i].item_order_lines
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_order_lines" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderLineQuery) loadLocation(ctx context.Context, query *LocationQuery, nodes []*OrderLine, init func(*OrderLine), assign func(*OrderLine, *Location)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderLine)
	for i := range nodes {
		if nodes[i].location_order_lines == nil {
			continue
		}
		fk := *nodes[i].location_order_lines
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(location.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "location_order_lines" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderLineQuery) loadPickTasks(ctx context.Context, query *PickTaskQuery, nodes []*OrderLine, init func(*OrderLine), assign func(*OrderLine, *PickTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*OrderLine)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PickTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(orderline.PickTasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.order_line_pick_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "order_line_pick_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_line_pick_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *OrderLineQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OrderLineQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderline.Table, orderline.Columns, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderline.FieldID)
		for i := range fields {
			if fields[i] != orderline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OrderLineQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(orderline.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = orderline.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderLineGroupBy is the group-by builder for OrderLine entities.
type OrderLineGroupBy struct {
	selector
	build *OrderLineQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OrderLineGroupBy) Aggregate(fns ...AggregateFunc) *OrderLineGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OrderLineGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderLineQuery, *OrderLineGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OrderLineGroupBy) sqlScan(ctx context.Context, root *OrderLineQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderLineSelect is the builder for selecting fields of OrderLine entities.
type OrderLineSelect struct {
	*OrderLineQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OrderLineSelect) Aggregate(fns ...AggregateFunc) *OrderLineSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OrderLineSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderLineQuery, *OrderLineSelect](ctx, _s.OrderLineQuery, _s, _s.inters, v)
}

func (_s *OrderLineSelect) sqlScan(ctx context.Context, root *OrderLineQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
