// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/item"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picktask"
)

// OrderLineCreate is the builder for creating a OrderLine entity.
type OrderLineCreate struct {
	config
	mutation *OrderLineMutation
	hooks    []Hook
}

// SetQuantity sets the "quantity" field.
func (_c *OrderLineCreate) SetQuantity(v int) *OrderLineCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_c *OrderLineCreate) SetOrderID(id int) *OrderLineCreate {
	_c.mutation.SetOrderID(id)
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *OrderLineCreate) SetOrder(v *Order) *OrderLineCreate {
	return _c.SetOrderID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_c *OrderLineCreate) SetItemID(id int) *OrderLineCreate {
	_c.mutation.SetItemID(id)
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *OrderLineCreate) SetItem(v *Item) *OrderLineCreate {
	return _c.SetItemID(v.ID)
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (_c *OrderLineCreate) SetLocationID(id int) *OrderLineCreate {
	_c.mutation.SetLocationID(id)
	return _c
}

// SetLocation sets the "location" edge to the Location entity.
func (_c *OrderLineCreate) SetLocation(v *Location) *OrderLineCreate {
	return _c.SetLocationID(v.ID)
}

// AddPickTaskIDs adds the "pick_tasks" edge to the PickTask entity by IDs.
func (_c *OrderLineCreate) AddPickTaskIDs(ids ...int) *OrderLineCreate {
	_c.mutation.AddPickTaskIDs(ids...)
	return _c
}

// AddPickTasks adds the "pick_tasks" edges to the PickTask entity.
func (_c *OrderLineCreate) AddPickTasks(v ...*PickTask) *OrderLineCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPickTaskIDs(ids...)
}

// Mutation returns the OrderLineMutation object of the builder.
func (_c *OrderLineCreate) Mutation() *OrderLineMutation {
	return _c.mutation
}

// Save creates the OrderLine in the database.
func (_c *OrderLineCreate) Save(ctx context.Context) (*OrderLine, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderLineCreate) SaveX(ctx context.Context) *OrderLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderLineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderLineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderLineCreate) check() error {
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "OrderLine.quantity"`)}
	}
	if v, ok := _c.mutation.Quantity(); ok {
		if err := orderline.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderLine.quantity": %w`, err)}
		}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "OrderLine.order"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "OrderLine.item"`)}
	}
	if len(_c.mutation.LocationIDs()) == 0 {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required edge "OrderLine.location"`)}
	}
	return nil
}

func (_c *OrderLineCreate) sqlSave(ctx context.Context) (*OrderLine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderLineCreate) createSpec() (*OrderLine, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderLine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orderline.Table, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(orderline.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.OrderTable,
			Columns: []string{orderline.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_lines = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.ItemTable,
			Columns: []string{orderline.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_order_lines = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.LocationTable,
			Columns: []string{orderline.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.location_order_lines = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PickTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderline.PickTasksTable,
			Columns: []string{orderline.PickTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderLineCreateBulk is the builder for creating many OrderLine entities in bulk.
type OrderLineCreateBulk struct {
	config
	err      error
	builders []*OrderLineCreate
}

// Save creates the OrderLine entities in the database.
func (_c *OrderLineCreateBulk) Save(ctx context.Context) ([]*OrderLine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderLine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderLineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderLineCreateBulk) SaveX(ctx context.Context) []*OrderLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderLineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderLineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
