// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/predicate"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *OrderUpdate) SetOrderNumber(v string) *OrderUpdate {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderNumber(v *string) *OrderUpdate {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdate) SetType(v string) *OrderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableType(v *string) *OrderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderUpdate) SetCreatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCreatedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddLineIDs adds the "lines" edge to the OrderLine entity by IDs.
func (_u *OrderUpdate) AddLineIDs(ids ...int) *OrderUpdate {
	_u.mutation.AddLineIDs(ids...)
	return _u
}

// AddLines adds the "lines" edges to the OrderLine entity.
func (_u *OrderUpdate) AddLines(v ...*OrderLine) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLineIDs(ids...)
}

// SetPicklistID sets the "picklist" edge to the PickList entity by ID.
func (_u *OrderUpdate) SetPicklistID(id int) *OrderUpdate {
	_u.mutation.SetPicklistID(id)
	return _u
}

// SetNillablePicklistID sets the "picklist" edge to the PickList entity by ID if the given value is not nil.
func (_u *OrderUpdate) SetNillablePicklistID(id *int) *OrderUpdate {
	if id != nil {
		_u = _u.SetPicklistID(*id)
	}
	return _u
}

// SetPicklist sets the "picklist" edge to the PickList entity.
func (_u *OrderUpdate) SetPicklist(v *PickList) *OrderUpdate {
	return _u.SetPicklistID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearLines clears all "lines" edges to the OrderLine entity.
func (_u *OrderUpdate) ClearLines() *OrderUpdate {
	_u.mutation.ClearLines()
	return _u
}

// RemoveLineIDs removes the "lines" edge to OrderLine entities by IDs.
func (_u *OrderUpdate) RemoveLineIDs(ids ...int) *OrderUpdate {
	_u.mutation.RemoveLineIDs(ids...)
	return _u
}

// RemoveLines removes "lines" edges to OrderLine entities.
func (_u *OrderUpdate) RemoveLines(v ...*OrderLine) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLineIDs(ids...)
}

// ClearPicklist clears the "picklist" edge to the PickList entity.
func (_u *OrderUpdate) ClearPicklist() *OrderUpdate {
	_u.mutation.ClearPicklist()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := order.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "Order.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(order.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinesIDs(); len(nodes) > 0 && !_u.mutation.LinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PicklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   order.PicklistTable,
			Columns: []string{order.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   order.PicklistTable,
			Columns: []string{order.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderNumber sets the "order_number" field.
func (_u *OrderUpdateOne) SetOrderNumber(v string) *OrderUpdateOne {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderNumber(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdateOne) SetType(v string) *OrderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableType(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderUpdateOne) SetCreatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCreatedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddLineIDs adds the "lines" edge to the OrderLine entity by IDs.
func (_u *OrderUpdateOne) AddLineIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.AddLineIDs(ids...)
	return _u
}

// AddLines adds the "lines" edges to the OrderLine entity.
func (_u *OrderUpdateOne) AddLines(v ...*OrderLine) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLineIDs(ids...)
}

// SetPicklistID sets the "picklist" edge to the PickList entity by ID.
func (_u *OrderUpdateOne) SetPicklistID(id int) *OrderUpdateOne {
	_u.mutation.SetPicklistID(id)
	return _u
}

// SetNillablePicklistID sets the "picklist" edge to the PickList entity by ID if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePicklistID(id *int) *OrderUpdateOne {
	if id != nil {
		_u = _u.SetPicklistID(*id)
	}
	return _u
}

// SetPicklist sets the "picklist" edge to the PickList entity.
func (_u *OrderUpdateOne) SetPicklist(v *PickList) *OrderUpdateOne {
	return _u.SetPicklistID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearLines clears all "lines" edges to the OrderLine entity.
func (_u *OrderUpdateOne) ClearLines() *OrderUpdateOne {
	_u.mutation.ClearLines()
	return _u
}

// RemoveLineIDs removes the "lines" edge to OrderLine entities by IDs.
func (_u *OrderUpdateOne) RemoveLineIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.RemoveLineIDs(ids...)
	return _u
}

// RemoveLines removes "lines" edges to OrderLine entities.
func (_u *OrderUpdateOne) RemoveLines(v ...*OrderLine) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLineIDs(ids...)
}

// ClearPicklist clears the "picklist" edge to the PickList entity.
func (_u *OrderUpdateOne) ClearPicklist() *OrderUpdateOne {
	_u.mutation.ClearPicklist()
	return _u
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := order.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "Order.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(order.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinesIDs(); len(nodes) > 0 && !_u.mutation.LinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LinesTable,
			Columns: []string{order.LinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PicklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   order.PicklistTable,
			Columns: []string{order.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   order.PicklistTable,
			Columns: []string{order.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
