// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/picktask"
	"github.com/mxV03/wms/ent/predicate"
)

// PickListUpdate is the builder for updating PickList entities.
type PickListUpdate struct {
	config
	hooks    []Hook
	mutation *PickListMutation
}

// Where appends a list predicates to the PickListUpdate builder.
func (_u *PickListUpdate) Where(ps ...predicate.PickList) *PickListUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PickListUpdate) SetStatus(v string) *PickListUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PickListUpdate) SetNillableStatus(v *string) *PickListUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PickListUpdate) SetCreatedAt(v time.Time) *PickListUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PickListUpdate) SetNillableCreatedAt(v *time.Time) *PickListUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PickListUpdate) SetStartedAt(v time.Time) *PickListUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PickListUpdate) SetNillableStartedAt(v *time.Time) *PickListUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *PickListUpdate) ClearStartedAt() *PickListUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetDoneAt sets the "done_at" field.
func (_u *PickListUpdate) SetDoneAt(v time.Time) *PickListUpdate {
	_u.mutation.SetDoneAt(v)
	return _u
}

// SetNillableDoneAt sets the "done_at" field if the given value is not nil.
func (_u *PickListUpdate) SetNillableDoneAt(v *time.Time) *PickListUpdate {
	if v != nil {
		_u.SetDoneAt(*v)
	}
	return _u
}

// ClearDoneAt clears the value of the "done_at" field.
func (_u *PickListUpdate) ClearDoneAt() *PickListUpdate {
	_u.mutation.ClearDoneAt()
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *PickListUpdate) SetOrderID(id int) *PickListUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *PickListUpdate) SetOrder(v *Order) *PickListUpdate {
	return _u.SetOrderID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the PickTask entity by IDs.
func (_u *PickListUpdate) AddTaskIDs(ids ...int) *PickListUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the PickTask entity.
func (_u *PickListUpdate) AddTasks(v ...*PickTask) *PickListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the PickListMutation object of the builder.
func (_u *PickListUpdate) Mutation() *PickListMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *PickListUpdate) ClearOrder() *PickListUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearTasks clears all "tasks" edges to the PickTask entity.
func (_u *PickListUpdate) ClearTasks() *PickListUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to PickTask entities by IDs.
func (_u *PickListUpdate) RemoveTaskIDs(ids ...int) *PickListUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to PickTask entities.
func (_u *PickListUpdate) RemoveTasks(v ...*PickTask) *PickListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PickListUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickListUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PickListUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickListUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickListUpdate) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickList.order"`)
	}
	return nil
}

func (_u *PickListUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(picklist.Table, picklist.Columns, sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(picklist.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(picklist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(picklist.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(picklist.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DoneAt(); ok {
		_spec.SetField(picklist.FieldDoneAt, field.TypeTime, value)
	}
	if _u.mutation.DoneAtCleared() {
		_spec.ClearField(picklist.FieldDoneAt, field.TypeTime)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   picklist.OrderTable,
			Columns: []string{picklist.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   picklist.OrderTable,
			Columns: []string{picklist.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picklist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PickListUpdateOne is the builder for updating a single PickList entity.
type PickListUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PickListMutation
}

// SetStatus sets the "status" field.
func (_u *PickListUpdateOne) SetStatus(v string) *PickListUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PickListUpdateOne) SetNillableStatus(v *string) *PickListUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PickListUpdateOne) SetCreatedAt(v time.Time) *PickListUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PickListUpdateOne) SetNillableCreatedAt(v *time.Time) *PickListUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PickListUpdateOne) SetStartedAt(v time.Time) *PickListUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PickListUpdateOne) SetNillableStartedAt(v *time.Time) *PickListUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *PickListUpdateOne) ClearStartedAt() *PickListUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetDoneAt sets the "done_at" field.
func (_u *PickListUpdateOne) SetDoneAt(v time.Time) *PickListUpdateOne {
	_u.mutation.SetDoneAt(v)
	return _u
}

// SetNillableDoneAt sets the "done_at" field if the given value is not nil.
func (_u *PickListUpdateOne) SetNillableDoneAt(v *time.Time) *PickListUpdateOne {
	if v != nil {
		_u.SetDoneAt(*v)
	}
	return _u
}

// ClearDoneAt clears the value of the "done_at" field.
func (_u *PickListUpdateOne) ClearDoneAt() *PickListUpdateOne {
	_u.mutation.ClearDoneAt()
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *PickListUpdateOne) SetOrderID(id int) *PickListUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *PickListUpdateOne) SetOrder(v *Order) *PickListUpdateOne {
	return _u.SetOrderID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the PickTask entity by IDs.
func (_u *PickListUpdateOne) AddTaskIDs(ids ...int) *PickListUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the PickTask entity.
func (_u *PickListUpdateOne) AddTasks(v ...*PickTask) *PickListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the PickListMutation object of the builder.
func (_u *PickListUpdateOne) Mutation() *PickListMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *PickListUpdateOne) ClearOrder() *PickListUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearTasks clears all "tasks" edges to the PickTask entity.
func (_u *PickListUpdateOne) ClearTasks() *PickListUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to PickTask entities by IDs.
func (_u *PickListUpdateOne) RemoveTaskIDs(ids ...int) *PickListUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to PickTask entities.
func (_u *PickListUpdateOne) RemoveTasks(v ...*PickTask) *PickListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the PickListUpdate builder.
func (_u *PickListUpdateOne) Where(ps ...predicate.PickList) *PickListUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PickListUpdateOne) Select(field string, fields ...string) *PickListUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PickList entity.
func (_u *PickListUpdateOne) Save(ctx context.Context) (*PickList, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickListUpdateOne) SaveX(ctx context.Context) *PickList {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PickListUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickListUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickListUpdateOne) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickList.order"`)
	}
	return nil
}

func (_u *PickListUpdateOne) sqlSave(ctx context.Context) (_node *PickList, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(picklist.Table, picklist.Columns, sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PickList.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, picklist.FieldID)
		for _, f := range fields {
			if !picklist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != picklist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(picklist.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(picklist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(picklist.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(picklist.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DoneAt(); ok {
		_spec.SetField(picklist.FieldDoneAt, field.TypeTime, value)
	}
	if _u.mutation.DoneAtCleared() {
		_spec.ClearField(picklist.FieldDoneAt, field.TypeTime)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   picklist.OrderTable,
			Columns: []string{picklist.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   picklist.OrderTable,
			Columns: []string{picklist.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PickList{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picklist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
