// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/picklist"
)

// PickList is the model entity for the PickList schema.
type PickList struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// DoneAt holds the value of the "done_at" field.
	DoneAt *time.Time `json:"done_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PickListQuery when eager-loading is set.
	Edges          PickListEdges `json:"edges"`
	order_picklist *int
	selectValues   sql.SelectValues
}

// PickListEdges holds the relations/edges for other nodes in the graph.
type PickListEdges struct {
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*PickTask `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PickListEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e PickListEdges) TasksOrErr() ([]*PickTask, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PickList) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case picklist.FieldID:
			values[i] = new(sql.NullInt64)
		case picklist.FieldStatus:
			values[i] = new(sql.NullString)
		case picklist.FieldCreatedAt, picklist.FieldStartedAt, picklist.FieldDoneAt:
			values[i] = new(sql.NullTime)
		case picklist.ForeignKeys[0]: // order_picklist
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PickList fields.
func (_m *PickList) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case picklist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case picklist.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case picklist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case picklist.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case picklist.FieldDoneAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field done_at", values[i])
			} else if value.Valid {
				_m.DoneAt = new(time.Time)
				*_m.DoneAt = value.Time
			}
		case picklist.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_picklist", value)
			} else if value.Valid {
				_m.order_picklist = new(int)
				*_m.order_picklist = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PickList.
// This includes values selected through modifiers, order, etc.
func (_m *PickList) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the PickList entity.
func (_m *PickList) QueryOrder() *OrderQuery {
	return NewPickListClient(_m.config).QueryOrder(_m)
}

// QueryTasks queries the "tasks" edge of the PickList entity.
func (_m *PickList) QueryTasks() *PickTaskQuery {
	return NewPickListClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this PickList.
// Note that you need to call PickList.Unwrap() before calling this method if this PickList
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PickList) Update() *PickListUpdateOne {
	return NewPickListClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PickList entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PickList) Unwrap() *PickList {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PickList is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PickList) String() string {
	var builder strings.Builder
	builder.WriteString("PickList(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DoneAt; v != nil {
		builder.WriteString("done_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PickLists is a parsable slice of PickList.
type PickLists []*PickList
