// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/picktask"
	"github.com/mxV03/wms/ent/predicate"
)

// PickTaskUpdate is the builder for updating PickTask entities.
type PickTaskUpdate struct {
	config
	hooks    []Hook
	mutation *PickTaskMutation
}

// Where appends a list predicates to the PickTaskUpdate builder.
func (_u *PickTaskUpdate) Where(ps ...predicate.PickTask) *PickTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PickTaskUpdate) SetQuantity(v int) *PickTaskUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PickTaskUpdate) SetNillableQuantity(v *int) *PickTaskUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PickTaskUpdate) AddQuantity(v int) *PickTaskUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PickTaskUpdate) SetStatus(v string) *PickTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PickTaskUpdate) SetNillableStatus(v *string) *PickTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPickedAt sets the "picked_at" field.
func (_u *PickTaskUpdate) SetPickedAt(v time.Time) *PickTaskUpdate {
	_u.mutation.SetPickedAt(v)
	return _u
}

// SetNillablePickedAt sets the "picked_at" field if the given value is not nil.
func (_u *PickTaskUpdate) SetNillablePickedAt(v *time.Time) *PickTaskUpdate {
	if v != nil {
		_u.SetPickedAt(*v)
	}
	return _u
}

// ClearPickedAt clears the value of the "picked_at" field.
func (_u *PickTaskUpdate) ClearPickedAt() *PickTaskUpdate {
	_u.mutation.ClearPickedAt()
	return _u
}

// SetBinID sets the "bin_id" field.
func (_u *PickTaskUpdate) SetBinID(v int) *PickTaskUpdate {
	_u.mutation.ResetBinID()
	_u.mutation.SetBinID(v)
	return _u
}

// SetNillableBinID sets the "bin_id" field if the given value is not nil.
func (_u *PickTaskUpdate) SetNillableBinID(v *int) *PickTaskUpdate {
	if v != nil {
		_u.SetBinID(*v)
	}
	return _u
}

// AddBinID adds value to the "bin_id" field.
func (_u *PickTaskUpdate) AddBinID(v int) *PickTaskUpdate {
	_u.mutation.AddBinID(v)
	return _u
}

// ClearBinID clears the value of the "bin_id" field.
func (_u *PickTaskUpdate) ClearBinID() *PickTaskUpdate {
	_u.mutation.ClearBinID()
	return _u
}

// SetPicklistID sets the "picklist" edge to the PickList entity by ID.
func (_u *PickTaskUpdate) SetPicklistID(id int) *PickTaskUpdate {
	_u.mutation.SetPicklistID(id)
	return _u
}

// SetPicklist sets the "picklist" edge to the PickList entity.
func (_u *PickTaskUpdate) SetPicklist(v *PickList) *PickTaskUpdate {
	return _u.SetPicklistID(v.ID)
}

// SetOrderLineID sets the "order_line" edge to the OrderLine entity by ID.
func (_u *PickTaskUpdate) SetOrderLineID(id int) *PickTaskUpdate {
	_u.mutation.SetOrderLineID(id)
	return _u
}

// SetOrderLine sets the "order_line" edge to the OrderLine entity.
func (_u *PickTaskUpdate) SetOrderLine(v *OrderLine) *PickTaskUpdate {
	return _u.SetOrderLineID(v.ID)
}

// Mutation returns the PickTaskMutation object of the builder.
func (_u *PickTaskUpdate) Mutation() *PickTaskMutation {
	return _u.mutation
}

// ClearPicklist clears the "picklist" edge to the PickList entity.
func (_u *PickTaskUpdate) ClearPicklist() *PickTaskUpdate {
	_u.mutation.ClearPicklist()
	return _u
}

// ClearOrderLine clears the "order_line" edge to the OrderLine entity.
func (_u *PickTaskUpdate) ClearOrderLine() *PickTaskUpdate {
	_u.mutation.ClearOrderLine()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PickTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PickTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickTaskUpdate) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := picktask.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "PickTask.quantity": %w`, err)}
		}
	}
	if _u.mutation.PicklistCleared() && len(_u.mutation.PicklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickTask.picklist"`)
	}
	if _u.mutation.OrderLineCleared() && len(_u.mutation.OrderLineIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickTask.order_line"`)
	}
	return nil
}

func (_u *PickTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(picktask.Table, picktask.Columns, sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(picktask.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(picktask.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(picktask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickedAt(); ok {
		_spec.SetField(picktask.FieldPickedAt, field.TypeTime, value)
	}
	if _u.mutation.PickedAtCleared() {
		_spec.ClearField(picktask.FieldPickedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BinID(); ok {
		_spec.SetField(picktask.FieldBinID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBinID(); ok {
		_spec.AddField(picktask.FieldBinID, field.TypeInt, value)
	}
	if _u.mutation.BinIDCleared() {
		_spec.ClearField(picktask.FieldBinID, field.TypeInt)
	}
	if _u.mutation.PicklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.PicklistTable,
			Columns: []string{picktask.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.PicklistTable,
			Columns: []string{picktask.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.OrderLineTable,
			Columns: []string{picktask.OrderLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderLineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.OrderLineTable,
			Columns: []string{picktask.OrderLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picktask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PickTaskUpdateOne is the builder for updating a single PickTask entity.
type PickTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PickTaskMutation
}

// SetQuantity sets the "quantity" field.
func (_u *PickTaskUpdateOne) SetQuantity(v int) *PickTaskUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PickTaskUpdateOne) SetNillableQuantity(v *int) *PickTaskUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PickTaskUpdateOne) AddQuantity(v int) *PickTaskUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PickTaskUpdateOne) SetStatus(v string) *PickTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PickTaskUpdateOne) SetNillableStatus(v *string) *PickTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPickedAt sets the "picked_at" field.
func (_u *PickTaskUpdateOne) SetPickedAt(v time.Time) *PickTaskUpdateOne {
	_u.mutation.SetPickedAt(v)
	return _u
}

// SetNillablePickedAt sets the "picked_at" field if the given value is not nil.
func (_u *PickTaskUpdateOne) SetNillablePickedAt(v *time.Time) *PickTaskUpdateOne {
	if v != nil {
		_u.SetPickedAt(*v)
	}
	return _u
}

// ClearPickedAt clears the value of the "picked_at" field.
func (_u *PickTaskUpdateOne) ClearPickedAt() *PickTaskUpdateOne {
	_u.mutation.ClearPickedAt()
	return _u
}

// SetBinID sets the "bin_id" field.
func (_u *PickTaskUpdateOne) SetBinID(v int) *PickTaskUpdateOne {
	_u.mutation.ResetBinID()
	_u.mutation.SetBinID(v)
	return _u
}

// SetNillableBinID sets the "bin_id" field if the given value is not nil.
func (_u *PickTaskUpdateOne) SetNillableBinID(v *int) *PickTaskUpdateOne {
	if v != nil {
		_u.SetBinID(*v)
	}
	return _u
}

// AddBinID adds value to the "bin_id" field.
func (_u *PickTaskUpdateOne) AddBinID(v int) *PickTaskUpdateOne {
	_u.mutation.AddBinID(v)
	return _u
}

// ClearBinID clears the value of the "bin_id" field.
func (_u *PickTaskUpdateOne) ClearBinID() *PickTaskUpdateOne {
	_u.mutation.ClearBinID()
	return _u
}

// SetPicklistID sets the "picklist" edge to the PickList entity by ID.
func (_u *PickTaskUpdateOne) SetPicklistID(id int) *PickTaskUpdateOne {
	_u.mutation.SetPicklistID(id)
	return _u
}

// SetPicklist sets the "picklist" edge to the PickList entity.
func (_u *PickTaskUpdateOne) SetPicklist(v *PickList) *PickTaskUpdateOne {
	return _u.SetPicklistID(v.ID)
}

// SetOrderLineID sets the "order_line" edge to the OrderLine entity by ID.
func (_u *PickTaskUpdateOne) SetOrderLineID(id int) *PickTaskUpdateOne {
	_u.mutation.SetOrderLineID(id)
	return _u
}

// SetOrderLine sets the "order_line" edge to the OrderLine entity.
func (_u *PickTaskUpdateOne) SetOrderLine(v *OrderLine) *PickTaskUpdateOne {
	return _u.SetOrderLineID(v.ID)
}

// Mutation returns the PickTaskMutation object of the builder.
func (_u *PickTaskUpdateOne) Mutation() *PickTaskMutation {
	return _u.mutation
}

// ClearPicklist clears the "picklist" edge to the PickList entity.
func (_u *PickTaskUpdateOne) ClearPicklist() *PickTaskUpdateOne {
	_u.mutation.ClearPicklist()
	return _u
}

// ClearOrderLine clears the "order_line" edge to the OrderLine entity.
func (_u *PickTaskUpdateOne) ClearOrderLine() *PickTaskUpdateOne {
	_u.mutation.ClearOrderLine()
	return _u
}

// Where appends a list predicates to the PickTaskUpdate builder.
func (_u *PickTaskUpdateOne) Where(ps ...predicate.PickTask) *PickTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PickTaskUpdateOne) Select(field string, fields ...string) *PickTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PickTask entity.
func (_u *PickTaskUpdateOne) Save(ctx context.Context) (*PickTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickTaskUpdateOne) SaveX(ctx context.Context) *PickTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PickTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := picktask.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "PickTask.quantity": %w`, err)}
		}
	}
	if _u.mutation.PicklistCleared() && len(_u.mutation.PicklistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickTask.picklist"`)
	}
	if _u.mutation.OrderLineCleared() && len(_u.mutation.OrderLineIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PickTask.order_line"`)
	}
	return nil
}

func (_u *PickTaskUpdateOne) sqlSave(ctx context.Context) (_node *PickTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(picktask.Table, picktask.Columns, sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PickTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, picktask.FieldID)
		for _, f := range fields {
			if !picktask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != picktask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(picktask.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(picktask.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(picktask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickedAt(); ok {
		_spec.SetField(picktask.FieldPickedAt, field.TypeTime, value)
	}
	if _u.mutation.PickedAtCleared() {
		_spec.ClearField(picktask.FieldPickedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BinID(); ok {
		_spec.SetField(picktask.FieldBinID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBinID(); ok {
		_spec.AddField(picktask.FieldBinID, field.TypeInt, value)
	}
	if _u.mutation.BinIDCleared() {
		_spec.ClearField(picktask.FieldBinID, field.TypeInt)
	}
	if _u.mutation.PicklistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.PicklistTable,
			Columns: []string{picktask.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.PicklistTable,
			Columns: []string{picktask.PicklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.OrderLineTable,
			Columns: []string{picktask.OrderLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderLineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picktask.OrderLineTable,
			Columns: []string{picktask.OrderLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PickTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picktask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
