// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/picktask"
)

// PickListCreate is the builder for creating a PickList entity.
type PickListCreate struct {
	config
	mutation *PickListMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *PickListCreate) SetStatus(v string) *PickListCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PickListCreate) SetNillableStatus(v *string) *PickListCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PickListCreate) SetCreatedAt(v time.Time) *PickListCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PickListCreate) SetNillableCreatedAt(v *time.Time) *PickListCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *PickListCreate) SetStartedAt(v time.Time) *PickListCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *PickListCreate) SetNillableStartedAt(v *time.Time) *PickListCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetDoneAt sets the "done_at" field.
func (_c *PickListCreate) SetDoneAt(v time.Time) *PickListCreate {
	_c.mutation.SetDoneAt(v)
	return _c
}

// SetNillableDoneAt sets the "done_at" field if the given value is not nil.
func (_c *PickListCreate) SetNillableDoneAt(v *time.Time) *PickListCreate {
	if v != nil {
		_c.SetDoneAt(*v)
	}
	return _c
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_c *PickListCreate) SetOrderID(id int) *PickListCreate {
	_c.mutation.SetOrderID(id)
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *PickListCreate) SetOrder(v *Order) *PickListCreate {
	return _c.SetOrderID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the PickTask entity by IDs.
func (_c *PickListCreate) AddTaskIDs(ids ...int) *PickListCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the PickTask entity.
func (_c *PickListCreate) AddTasks(v ...*PickTask) *PickListCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the PickListMutation object of the builder.
func (_c *PickListCreate) Mutation() *PickListMutation {
	return _c.mutation
}

// Save creates the PickList in the database.
func (_c *PickListCreate) Save(ctx context.Context) (*PickList, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PickListCreate) SaveX(ctx context.Context) *PickList {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PickListCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PickListCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PickListCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := picklist.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := picklist.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PickListCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PickList.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PickList.created_at"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "PickList.order"`)}
	}
	return nil
}

func (_c *PickListCreate) sqlSave(ctx context.Context) (*PickList, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PickListCreate) createSpec() (*PickList, *sqlgraph.CreateSpec) {
	var (
		_node = &PickList{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(picklist.Table, sqlgraph.NewFieldSpec(picklist.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(picklist.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(picklist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(picklist.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.DoneAt(); ok {
		_spec.SetField(picklist.FieldDoneAt, field.TypeTime, value)
		_node.DoneAt = &value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   picklist.OrderTable,
			Columns: []string{picklist.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_picklist = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   picklist.TasksTable,
			Columns: []string{picklist.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(picktask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PickListCreateBulk is the builder for creating many PickList entities in bulk.
type PickListCreateBulk struct {
	config
	err      error
	builders []*PickListCreate
}

// Save creates the PickList entities in the database.
func (_c *PickListCreateBulk) Save(ctx context.Context) ([]*PickList, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PickList, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PickListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PickListCreateBulk) SaveX(ctx context.Context) []*PickList {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PickListCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PickListCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
