// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mxV03/wms/ent/auditevent"
	"github.com/mxV03/wms/ent/bin"
	"github.com/mxV03/wms/ent/item"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/orderline"
	"github.com/mxV03/wms/ent/picklist"
	"github.com/mxV03/wms/ent/picktask"
	"github.com/mxV03/wms/ent/schema"
	"github.com/mxV03/wms/ent/stockmovement"
	"github.com/mxV03/wms/ent/tracking"
	"github.com/mxV03/wms/ent/user"
	"github.com/mxV03/wms/ent/zone"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescTs is the schema descriptor for ts field.
	auditeventDescTs := auditeventFields[0].Descriptor()
	// auditevent.DefaultTs holds the default value on creation for the ts field.
	auditevent.DefaultTs = auditeventDescTs.Default.(func() time.Time)
	// auditeventDescAction is the schema descriptor for action field.
	auditeventDescAction := auditeventFields[1].Descriptor()
	// auditevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditevent.ActionValidator = auditeventDescAction.Validators[0].(func(string) error)
	// auditeventDescEntity is the schema descriptor for entity field.
	auditeventDescEntity := auditeventFields[2].Descriptor()
	// auditevent.EntityValidator is a validator for the "entity" field. It is called by the builders before save.
	auditevent.EntityValidator = auditeventDescEntity.Validators[0].(func(string) error)
	// auditeventDescEntityRef is the schema descriptor for entity_ref field.
	auditeventDescEntityRef := auditeventFields[3].Descriptor()
	// auditevent.DefaultEntityRef holds the default value on creation for the entity_ref field.
	auditevent.DefaultEntityRef = auditeventDescEntityRef.Default.(string)
	// auditeventDescActor is the schema descriptor for actor field.
	auditeventDescActor := auditeventFields[4].Descriptor()
	// auditevent.DefaultActor holds the default value on creation for the actor field.
	auditevent.DefaultActor = auditeventDescActor.Default.(string)
	// auditeventDescDetails is the schema descriptor for details field.
	auditeventDescDetails := auditeventFields[5].Descriptor()
	// auditevent.DefaultDetails holds the default value on creation for the details field.
	auditevent.DefaultDetails = auditeventDescDetails.Default.(string)
	binFields := schema.Bin{}.Fields()
	_ = binFields
	// binDescCode is the schema descriptor for code field.
	binDescCode := binFields[0].Descriptor()
	// bin.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	bin.CodeValidator = binDescCode.Validators[0].(func(string) error)
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescSKU is the schema descriptor for SKU field.
	itemDescSKU := itemFields[0].Descriptor()
	// item.SKUValidator is a validator for the "SKU" field. It is called by the builders before save.
	item.SKUValidator = itemDescSKU.Validators[0].(func(string) error)
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemFields[1].Descriptor()
	// item.NameValidator is a validator for the "name" field. It is called by the builders before save.
	item.NameValidator = itemDescName.Validators[0].(func(string) error)
	locationFields := schema.Location{}.Fields()
	_ = locationFields
	// locationDescCode is the schema descriptor for code field.
	locationDescCode := locationFields[0].Descriptor()
	// location.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	location.CodeValidator = locationDescCode.Validators[0].(func(string) error)
	// locationDescName is the schema descriptor for name field.
	locationDescName := locationFields[1].Descriptor()
	// location.NameValidator is a validator for the "name" field. It is called by the builders before save.
	location.NameValidator = locationDescName.Validators[0].(func(string) error)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescOrderNumber is the schema descriptor for order_number field.
	orderDescOrderNumber := orderFields[0].Descriptor()
	// order.OrderNumberValidator is a validator for the "order_number" field. It is called by the builders before save.
	order.OrderNumberValidator = orderDescOrderNumber.Validators[0].(func(string) error)
	// orderDescType is the schema descriptor for type field.
	orderDescType := orderFields[1].Descriptor()
	// order.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	order.TypeValidator = orderDescType.Validators[0].(func(string) error)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[2].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// order.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	order.StatusValidator = orderDescStatus.Validators[0].(func(string) error)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[3].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	orderlineFields := schema.OrderLine{}.Fields()
	_ = orderlineFields
	// orderlineDescQuantity is the schema descriptor for quantity field.
	orderlineDescQuantity := orderlineFields[0].Descriptor()
	// orderline.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	orderline.QuantityValidator = orderlineDescQuantity.Validators[0].(func(int) error)
	picklistFields := schema.PickList{}.Fields()
	_ = picklistFields
	// picklistDescStatus is the schema descriptor for status field.
	picklistDescStatus := picklistFields[0].Descriptor()
	// picklist.DefaultStatus holds the default value on creation for the status field.
	picklist.DefaultStatus = picklistDescStatus.Default.(string)
	// picklistDescCreatedAt is the schema descriptor for created_at field.
	picklistDescCreatedAt := picklistFields[1].Descriptor()
	// picklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	picklist.DefaultCreatedAt = picklistDescCreatedAt.Default.(func() time.Time)
	picktaskFields := schema.PickTask{}.Fields()
	_ = picktaskFields
	// picktaskDescQuantity is the schema descriptor for quantity field.
	picktaskDescQuantity := picktaskFields[0].Descriptor()
	// picktask.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	picktask.QuantityValidator = picktaskDescQuantity.Validators[0].(func(int) error)
	// picktaskDescStatus is the schema descriptor for status field.
	picktaskDescStatus := picktaskFields[1].Descriptor()
	// picktask.DefaultStatus holds the default value on creation for the status field.
	picktask.DefaultStatus = picktaskDescStatus.Default.(string)
	stockmovementFields := schema.StockMovement{}.Fields()
	_ = stockmovementFields
	// stockmovementDescType is the schema descriptor for type field.
	stockmovementDescType := stockmovementFields[0].Descriptor()
	// stockmovement.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	stockmovement.TypeValidator = stockmovementDescType.Validators[0].(func(string) error)
	// stockmovementDescQuantity is the schema descriptor for quantity field.
	stockmovementDescQuantity := stockmovementFields[1].Descriptor()
	// stockmovement.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	stockmovement.QuantityValidator = stockmovementDescQuantity.Validators[0].(func(int) error)
	// stockmovementDescCreatedAt is the schema descriptor for created_at field.
	stockmovementDescCreatedAt := stockmovementFields[2].Descriptor()
	// stockmovement.DefaultCreatedAt holds the default value on creation for the created_at field.
	stockmovement.DefaultCreatedAt = stockmovementDescCreatedAt.Default.(func() time.Time)
	trackingFields := schema.Tracking{}.Fields()
	_ = trackingFields
	// trackingDescTrackingID is the schema descriptor for tracking_id field.
	trackingDescTrackingID := trackingFields[0].Descriptor()
	// tracking.TrackingIDValidator is a validator for the "tracking_id" field. It is called by the builders before save.
	tracking.TrackingIDValidator = trackingDescTrackingID.Validators[0].(func(string) error)
	// trackingDescTrackingURL is the schema descriptor for tracking_url field.
	trackingDescTrackingURL := trackingFields[1].Descriptor()
	// tracking.DefaultTrackingURL holds the default value on creation for the tracking_url field.
	tracking.DefaultTrackingURL = trackingDescTrackingURL.Default.(string)
	// trackingDescCarrier is the schema descriptor for carrier field.
	trackingDescCarrier := trackingFields[2].Descriptor()
	// tracking.DefaultCarrier holds the default value on creation for the carrier field.
	tracking.DefaultCarrier = trackingDescCarrier.Default.(string)
	// trackingDescCreatedAt is the schema descriptor for created_at field.
	trackingDescCreatedAt := trackingFields[3].Descriptor()
	// tracking.DefaultCreatedAt holds the default value on creation for the created_at field.
	tracking.DefaultCreatedAt = trackingDescCreatedAt.Default.(func() time.Time)
	// trackingDescUpdateAt is the schema descriptor for update_at field.
	trackingDescUpdateAt := trackingFields[4].Descriptor()
	// tracking.DefaultUpdateAt holds the default value on creation for the update_at field.
	tracking.DefaultUpdateAt = trackingDescUpdateAt.Default.(func() time.Time)
	// tracking.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	tracking.UpdateDefaultUpdateAt = trackingDescUpdateAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[3].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	zoneFields := schema.Zone{}.Fields()
	_ = zoneFields
	// zoneDescCode is the schema descriptor for code field.
	zoneDescCode := zoneFields[0].Descriptor()
	// zone.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	zone.CodeValidator = zoneDescCode.Validators[0].(func(string) error)
}
