// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/order"
	"github.com/mxV03/wms/ent/predicate"
	"github.com/mxV03/wms/ent/tracking"
)

// TrackingUpdate is the builder for updating Tracking entities.
type TrackingUpdate struct {
	config
	hooks    []Hook
	mutation *TrackingMutation
}

// Where appends a list predicates to the TrackingUpdate builder.
func (_u *TrackingUpdate) Where(ps ...predicate.Tracking) *TrackingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTrackingID sets the "tracking_id" field.
func (_u *TrackingUpdate) SetTrackingID(v string) *TrackingUpdate {
	_u.mutation.SetTrackingID(v)
	return _u
}

// SetNillableTrackingID sets the "tracking_id" field if the given value is not nil.
func (_u *TrackingUpdate) SetNillableTrackingID(v *string) *TrackingUpdate {
	if v != nil {
		_u.SetTrackingID(*v)
	}
	return _u
}

// SetTrackingURL sets the "tracking_url" field.
func (_u *TrackingUpdate) SetTrackingURL(v string) *TrackingUpdate {
	_u.mutation.SetTrackingURL(v)
	return _u
}

// SetNillableTrackingURL sets the "tracking_url" field if the given value is not nil.
func (_u *TrackingUpdate) SetNillableTrackingURL(v *string) *TrackingUpdate {
	if v != nil {
		_u.SetTrackingURL(*v)
	}
	return _u
}

// ClearTrackingURL clears the value of the "tracking_url" field.
func (_u *TrackingUpdate) ClearTrackingURL() *TrackingUpdate {
	_u.mutation.ClearTrackingURL()
	return _u
}

// SetCarrier sets the "carrier" field.
func (_u *TrackingUpdate) SetCarrier(v string) *TrackingUpdate {
	_u.mutation.SetCarrier(v)
	return _u
}

// SetNillableCarrier sets the "carrier" field if the given value is not nil.
func (_u *TrackingUpdate) SetNillableCarrier(v *string) *TrackingUpdate {
	if v != nil {
		_u.SetCarrier(*v)
	}
	return _u
}

// ClearCarrier clears the value of the "carrier" field.
func (_u *TrackingUpdate) ClearCarrier() *TrackingUpdate {
	_u.mutation.ClearCarrier()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TrackingUpdate) SetCreatedAt(v time.Time) *TrackingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TrackingUpdate) SetNillableCreatedAt(v *time.Time) *TrackingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *TrackingUpdate) SetUpdateAt(v time.Time) *TrackingUpdate {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *TrackingUpdate) SetOrderID(id int) *TrackingUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *TrackingUpdate) SetOrder(v *Order) *TrackingUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the TrackingMutation object of the builder.
func (_u *TrackingUpdate) Mutation() *TrackingMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *TrackingUpdate) ClearOrder() *TrackingUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrackingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrackingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TrackingUpdate) defaults() {
	if _, ok := _u.mutation.UpdateAt(); !ok {
		v := tracking.UpdateDefaultUpdateAt()
		_u.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackingUpdate) check() error {
	if v, ok := _u.mutation.TrackingID(); ok {
		if err := tracking.TrackingIDValidator(v); err != nil {
			return &ValidationError{Name: "tracking_id", err: fmt.Errorf(`ent: validator failed for field "Tracking.tracking_id": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tracking.order"`)
	}
	return nil
}

func (_u *TrackingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tracking.Table, tracking.Columns, sqlgraph.NewFieldSpec(tracking.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingID(); ok {
		_spec.SetField(tracking.FieldTrackingID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackingURL(); ok {
		_spec.SetField(tracking.FieldTrackingURL, field.TypeString, value)
	}
	if _u.mutation.TrackingURLCleared() {
		_spec.ClearField(tracking.FieldTrackingURL, field.TypeString)
	}
	if value, ok := _u.mutation.Carrier(); ok {
		_spec.SetField(tracking.FieldCarrier, field.TypeString, value)
	}
	if _u.mutation.CarrierCleared() {
		_spec.ClearField(tracking.FieldCarrier, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tracking.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(tracking.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tracking.OrderTable,
			Columns: []string{tracking.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tracking.OrderTable,
			Columns: []string{tracking.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tracking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrackingUpdateOne is the builder for updating a single Tracking entity.
type TrackingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackingMutation
}

// SetTrackingID sets the "tracking_id" field.
func (_u *TrackingUpdateOne) SetTrackingID(v string) *TrackingUpdateOne {
	_u.mutation.SetTrackingID(v)
	return _u
}

// SetNillableTrackingID sets the "tracking_id" field if the given value is not nil.
func (_u *TrackingUpdateOne) SetNillableTrackingID(v *string) *TrackingUpdateOne {
	if v != nil {
		_u.SetTrackingID(*v)
	}
	return _u
}

// SetTrackingURL sets the "tracking_url" field.
func (_u *TrackingUpdateOne) SetTrackingURL(v string) *TrackingUpdateOne {
	_u.mutation.SetTrackingURL(v)
	return _u
}

// SetNillableTrackingURL sets the "tracking_url" field if the given value is not nil.
func (_u *TrackingUpdateOne) SetNillableTrackingURL(v *string) *TrackingUpdateOne {
	if v != nil {
		_u.SetTrackingURL(*v)
	}
	return _u
}

// ClearTrackingURL clears the value of the "tracking_url" field.
func (_u *TrackingUpdateOne) ClearTrackingURL() *TrackingUpdateOne {
	_u.mutation.ClearTrackingURL()
	return _u
}

// SetCarrier sets the "carrier" field.
func (_u *TrackingUpdateOne) SetCarrier(v string) *TrackingUpdateOne {
	_u.mutation.SetCarrier(v)
	return _u
}

// SetNillableCarrier sets the "carrier" field if the given value is not nil.
func (_u *TrackingUpdateOne) SetNillableCarrier(v *string) *TrackingUpdateOne {
	if v != nil {
		_u.SetCarrier(*v)
	}
	return _u
}

// ClearCarrier clears the value of the "carrier" field.
func (_u *TrackingUpdateOne) ClearCarrier() *TrackingUpdateOne {
	_u.mutation.ClearCarrier()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TrackingUpdateOne) SetCreatedAt(v time.Time) *TrackingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TrackingUpdateOne) SetNillableCreatedAt(v *time.Time) *TrackingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdateAt sets the "update_at" field.
func (_u *TrackingUpdateOne) SetUpdateAt(v time.Time) *TrackingUpdateOne {
	_u.mutation.SetUpdateAt(v)
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *TrackingUpdateOne) SetOrderID(id int) *TrackingUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *TrackingUpdateOne) SetOrder(v *Order) *TrackingUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the TrackingMutation object of the builder.
func (_u *TrackingUpdateOne) Mutation() *TrackingMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *TrackingUpdateOne) ClearOrder() *TrackingUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the TrackingUpdate builder.
func (_u *TrackingUpdateOne) Where(ps ...predicate.Tracking) *TrackingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrackingUpdateOne) Select(field string, fields ...string) *TrackingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tracking entity.
func (_u *TrackingUpdateOne) Save(ctx context.Context) (*Tracking, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackingUpdateOne) SaveX(ctx context.Context) *Tracking {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrackingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TrackingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateAt(); !ok {
		v := tracking.UpdateDefaultUpdateAt()
		_u.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackingUpdateOne) check() error {
	if v, ok := _u.mutation.TrackingID(); ok {
		if err := tracking.TrackingIDValidator(v); err != nil {
			return &ValidationError{Name: "tracking_id", err: fmt.Errorf(`ent: validator failed for field "Tracking.tracking_id": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tracking.order"`)
	}
	return nil
}

func (_u *TrackingUpdateOne) sqlSave(ctx context.Context) (_node *Tracking, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tracking.Table, tracking.Columns, sqlgraph.NewFieldSpec(tracking.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tracking.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tracking.FieldID)
		for _, f := range fields {
			if !tracking.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tracking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingID(); ok {
		_spec.SetField(tracking.FieldTrackingID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackingURL(); ok {
		_spec.SetField(tracking.FieldTrackingURL, field.TypeString, value)
	}
	if _u.mutation.TrackingURLCleared() {
		_spec.ClearField(tracking.FieldTrackingURL, field.TypeString)
	}
	if value, ok := _u.mutation.Carrier(); ok {
		_spec.SetField(tracking.FieldCarrier, field.TypeString, value)
	}
	if _u.mutation.CarrierCleared() {
		_spec.ClearField(tracking.FieldCarrier, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tracking.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateAt(); ok {
		_spec.SetField(tracking.FieldUpdateAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tracking.OrderTable,
			Columns: []string{tracking.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tracking.OrderTable,
			Columns: []string{tracking.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tracking{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tracking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
