// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/predicate"
	"github.com/mxV03/wms/ent/warehouse"
	"github.com/mxV03/wms/ent/warehouselocation"
)

// WarehouseUpdate is the builder for updating Warehouse entities.
type WarehouseUpdate struct {
	config
	hooks    []Hook
	mutation *WarehouseMutation
}

// Where appends a list predicates to the WarehouseUpdate builder.
func (_u *WarehouseUpdate) Where(ps ...predicate.Warehouse) *WarehouseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *WarehouseUpdate) SetCode(v string) *WarehouseUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *WarehouseUpdate) SetNillableCode(v *string) *WarehouseUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WarehouseUpdate) SetName(v string) *WarehouseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WarehouseUpdate) SetNillableName(v *string) *WarehouseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WarehouseUpdate) ClearName() *WarehouseUpdate {
	_u.mutation.ClearName()
	return _u
}

// AddWarehouseLocationIDs adds the "warehouse_locations" edge to the WarehouseLocation entity by IDs.
func (_u *WarehouseUpdate) AddWarehouseLocationIDs(ids ...int) *WarehouseUpdate {
	_u.mutation.AddWarehouseLocationIDs(ids...)
	return _u
}

// AddWarehouseLocations adds the "warehouse_locations" edges to the WarehouseLocation entity.
func (_u *WarehouseUpdate) AddWarehouseLocations(v ...*WarehouseLocation) *WarehouseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWarehouseLocationIDs(ids...)
}

// Mutation returns the WarehouseMutation object of the builder.
func (_u *WarehouseUpdate) Mutation() *WarehouseMutation {
	return _u.mutation
}

// ClearWarehouseLocations clears all "warehouse_locations" edges to the WarehouseLocation entity.
func (_u *WarehouseUpdate) ClearWarehouseLocations() *WarehouseUpdate {
	_u.mutation.ClearWarehouseLocations()
	return _u
}

// RemoveWarehouseLocationIDs removes the "warehouse_locations" edge to WarehouseLocation entities by IDs.
func (_u *WarehouseUpdate) RemoveWarehouseLocationIDs(ids ...int) *WarehouseUpdate {
	_u.mutation.RemoveWarehouseLocationIDs(ids...)
	return _u
}

// RemoveWarehouseLocations removes "warehouse_locations" edges to WarehouseLocation entities.
func (_u *WarehouseUpdate) RemoveWarehouseLocations(v ...*WarehouseLocation) *WarehouseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWarehouseLocationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WarehouseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WarehouseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WarehouseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WarehouseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WarehouseUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := warehouse.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Warehouse.code": %w`, err)}
		}
	}
	return nil
}

func (_u *WarehouseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(warehouse.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(warehouse.FieldName, field.TypeString)
	}
	if _u.mutation.WarehouseLocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWarehouseLocationsIDs(); len(nodes) > 0 && !_u.mutation.WarehouseLocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseLocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{warehouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WarehouseUpdateOne is the builder for updating a single Warehouse entity.
type WarehouseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WarehouseMutation
}

// SetCode sets the "code" field.
func (_u *WarehouseUpdateOne) SetCode(v string) *WarehouseUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *WarehouseUpdateOne) SetNillableCode(v *string) *WarehouseUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WarehouseUpdateOne) SetName(v string) *WarehouseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WarehouseUpdateOne) SetNillableName(v *string) *WarehouseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WarehouseUpdateOne) ClearName() *WarehouseUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// AddWarehouseLocationIDs adds the "warehouse_locations" edge to the WarehouseLocation entity by IDs.
func (_u *WarehouseUpdateOne) AddWarehouseLocationIDs(ids ...int) *WarehouseUpdateOne {
	_u.mutation.AddWarehouseLocationIDs(ids...)
	return _u
}

// AddWarehouseLocations adds the "warehouse_locations" edges to the WarehouseLocation entity.
func (_u *WarehouseUpdateOne) AddWarehouseLocations(v ...*WarehouseLocation) *WarehouseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWarehouseLocationIDs(ids...)
}

// Mutation returns the WarehouseMutation object of the builder.
func (_u *WarehouseUpdateOne) Mutation() *WarehouseMutation {
	return _u.mutation
}

// ClearWarehouseLocations clears all "warehouse_locations" edges to the WarehouseLocation entity.
func (_u *WarehouseUpdateOne) ClearWarehouseLocations() *WarehouseUpdateOne {
	_u.mutation.ClearWarehouseLocations()
	return _u
}

// RemoveWarehouseLocationIDs removes the "warehouse_locations" edge to WarehouseLocation entities by IDs.
func (_u *WarehouseUpdateOne) RemoveWarehouseLocationIDs(ids ...int) *WarehouseUpdateOne {
	_u.mutation.RemoveWarehouseLocationIDs(ids...)
	return _u
}

// RemoveWarehouseLocations removes "warehouse_locations" edges to WarehouseLocation entities.
func (_u *WarehouseUpdateOne) RemoveWarehouseLocations(v ...*WarehouseLocation) *WarehouseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWarehouseLocationIDs(ids...)
}

// Where appends a list predicates to the WarehouseUpdate builder.
func (_u *WarehouseUpdateOne) Where(ps ...predicate.Warehouse) *WarehouseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WarehouseUpdateOne) Select(field string, fields ...string) *WarehouseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Warehouse entity.
func (_u *WarehouseUpdateOne) Save(ctx context.Context) (*Warehouse, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WarehouseUpdateOne) SaveX(ctx context.Context) *Warehouse {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WarehouseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WarehouseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WarehouseUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := warehouse.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Warehouse.code": %w`, err)}
		}
	}
	return nil
}

func (_u *WarehouseUpdateOne) sqlSave(ctx context.Context) (_node *Warehouse, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Warehouse.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, warehouse.FieldID)
		for _, f := range fields {
			if !warehouse.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != warehouse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(warehouse.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(warehouse.FieldName, field.TypeString)
	}
	if _u.mutation.WarehouseLocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWarehouseLocationsIDs(); len(nodes) > 0 && !_u.mutation.WarehouseLocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseLocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.WarehouseLocationsTable,
			Columns: []string{warehouse.WarehouseLocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouselocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Warehouse{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{warehouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
