// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mxV03/wms/ent/bin"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/zone"
)

// ZoneCreate is the builder for creating a Zone entity.
type ZoneCreate struct {
	config
	mutation *ZoneMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ZoneCreate) SetCode(v string) *ZoneCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ZoneCreate) SetName(v string) *ZoneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ZoneCreate) SetNillableName(v *string) *ZoneCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (_c *ZoneCreate) SetLocationID(id int) *ZoneCreate {
	_c.mutation.SetLocationID(id)
	return _c
}

// SetLocation sets the "location" edge to the Location entity.
func (_c *ZoneCreate) SetLocation(v *Location) *ZoneCreate {
	return _c.SetLocationID(v.ID)
}

// AddBinIDs adds the "bins" edge to the Bin entity by IDs.
func (_c *ZoneCreate) AddBinIDs(ids ...int) *ZoneCreate {
	_c.mutation.AddBinIDs(ids...)
	return _c
}

// AddBins adds the "bins" edges to the Bin entity.
func (_c *ZoneCreate) AddBins(v ...*Bin) *ZoneCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBinIDs(ids...)
}

// Mutation returns the ZoneMutation object of the builder.
func (_c *ZoneCreate) Mutation() *ZoneMutation {
	return _c.mutation
}

// Save creates the Zone in the database.
func (_c *ZoneCreate) Save(ctx context.Context) (*Zone, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ZoneCreate) SaveX(ctx context.Context) *Zone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ZoneCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Zone.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := zone.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Zone.code": %w`, err)}
		}
	}
	if len(_c.mutation.LocationIDs()) == 0 {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required edge "Zone.location"`)}
	}
	return nil
}

func (_c *ZoneCreate) sqlSave(ctx context.Context) (*Zone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ZoneCreate) createSpec() (*Zone, *sqlgraph.CreateSpec) {
	var (
		_node = &Zone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(zone.Table, sqlgraph.NewFieldSpec(zone.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(zone.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(zone.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zone.LocationTable,
			Columns: []string{zone.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.location_zones = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   zone.BinsTable,
			Columns: []string{zone.BinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ZoneCreateBulk is the builder for creating many Zone entities in bulk.
type ZoneCreateBulk struct {
	config
	err      error
	builders []*ZoneCreate
}

// Save creates the Zone entities in the database.
func (_c *ZoneCreateBulk) Save(ctx context.Context) ([]*Zone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Zone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ZoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ZoneCreateBulk) SaveX(ctx context.Context) []*Zone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
