// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mxV03/wms/ent/location"
	"github.com/mxV03/wms/ent/zone"
)

// Zone is the model entity for the Zone schema.
type Zone struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ZoneQuery when eager-loading is set.
	Edges          ZoneEdges `json:"edges"`
	location_zones *int
	selectValues   sql.SelectValues
}

// ZoneEdges holds the relations/edges for other nodes in the graph.
type ZoneEdges struct {
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// Bins holds the value of the bins edge.
	Bins []*Bin `json:"bins,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ZoneEdges) LocationOrErr() (*Location, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: location.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// BinsOrErr returns the Bins value or an error if the edge
// was not loaded in eager-loading.
func (e ZoneEdges) BinsOrErr() ([]*Bin, error) {
	if e.loadedTypes[1] {
		return e.Bins, nil
	}
	return nil, &NotLoadedError{edge: "bins"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Zone) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case zone.FieldID:
			values[i] = new(sql.NullInt64)
		case zone.FieldCode, zone.FieldName:
			values[i] = new(sql.NullString)
		case zone.ForeignKeys[0]: // location_zones
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Zone fields.
func (_m *Zone) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case zone.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case zone.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case zone.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case zone.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field location_zones", value)
			} else if value.Valid {
				_m.location_zones = new(int)
				*_m.location_zones = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Zone.
// This includes values selected through modifiers, order, etc.
func (_m *Zone) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLocation queries the "location" edge of the Zone entity.
func (_m *Zone) QueryLocation() *LocationQuery {
	return NewZoneClient(_m.config).QueryLocation(_m)
}

// QueryBins queries the "bins" edge of the Zone entity.
func (_m *Zone) QueryBins() *BinQuery {
	return NewZoneClient(_m.config).QueryBins(_m)
}

// Update returns a builder for updating this Zone.
// Note that you need to call Zone.Unwrap() before calling this method if this Zone
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Zone) Update() *ZoneUpdateOne {
	return NewZoneClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Zone entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Zone) Unwrap() *Zone {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Zone is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Zone) String() string {
	var builder strings.Builder
	builder.WriteString("Zone(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Zones is a parsable slice of Zone.
type Zones []*Zone
